-- ============================================================
-- KONKAN BAZAAR — Seed Data
-- 200+ Authentic Konkan Products Across All Categories
-- ============================================================

USE konkan_bazaar;

-- ============================================================
-- CATEGORIES (with parent-child hierarchy)
-- ============================================================
INSERT INTO categories (id, name, slug, description, image_url, parent_id, is_active, sort_order, meta_title, meta_description) VALUES
(1, 'Konkan Mangoes & Fruits', 'konkan-mangoes-fruits', 'Alphonso, Hapus, Payri, and other premium Konkan variety mangoes and tropical fruits', '/images/categories/mangoes.jpg', NULL, 1, 1, 'Buy Fresh Konkan Mangoes Online | Konkan Bazaar', 'Premium Alphonso, Hapus, Payri mangoes from Ratnagiri, Devgad, and Sindhudurg'),
(2, 'Coastal Seafood', 'coastal-seafood', 'Premium dried and fresh seafood including prawns, bombil, mackerel, and traditional Konkan fish', '/images/categories/seafood.jpg', NULL, 1, 2, 'Authentic Konkan Coastal Seafood Online | Konkan Bazaar', 'Premium dried fish, prawns, bombil, and fresh coastal seafood from the Konkan coast'),
(3, 'Coconut Products', 'coconut-products', 'Pure coconut oil, dried coconut, coconut milk, and traditional coconut-based products', '/images/categories/coconut.jpg', NULL, 1, 3, 'Pure Coconut Products Online | Konkan Bazaar', 'Cold-pressed coconut oil, dried coconut, and traditional coconut products from Konkan'),
(4, 'Konkan Rice Varieties', 'konkan-rice-varieties', 'Premium Indrayani, Ambemohar, Red Rice, and traditional Konkan rice varieties', '/images/categories/rice.jpg', NULL, 1, 4, 'Buy Authentic Konkan Rice Online | Konkan Bazaar', 'Premium Indrayani, Ambemohar, Red Rice, and traditional rice varieties from Konkan region'),
(5, 'Kokum & Beverages', 'kokum-beverages', 'Kokum juice, Sol Kadhi, and traditional Konkan cooling beverages', '/images/categories/kokum.jpg', NULL, 1, 5, 'Buy Kokum & Konkan Beverages Online | Konkan Bazaar', 'Refreshing Kokum juice, Sol Kadhi, and traditional Konkan beverages'),
(6, 'Pickles & Chutneys', 'pickles-chutneys', 'Traditional Konkan pickles, chutneys, and condiments made with authentic recipes', '/images/categories/pickles.jpg', NULL, 1, 6, 'Traditional Konkan Pickles & Chutneys Online | Konkan Bazaar', 'Authentic Konkan style pickles, chutneys, and traditional condiments'),
(7, 'Cashew & Dry Fruits', 'cashew-dry-fruits', 'Premium Konkan cashews, raw, roasted, spiced, and cashew Feni', '/images/categories/cashew.jpg', NULL, 1, 7, 'Premium Konkan Cashews Online | Konkan Bazaar', 'Premium cashew nuts from Goa and Konkan region - raw, roasted, and spiced varieties'),
(8, 'Natural Spices', 'natural-spices', 'Pure, organic spices from the Konkan region including black pepper, cardamom, cloves', '/images/categories/spices.jpg', NULL, 1, 8, 'Organic Konkan Spices Online | Konkan Bazaar', 'Pure organic spices from the Konkan region - pepper, cardamom, cloves, and more'),
(9, 'Organic Jaggery & Sweeteners', 'organic-jaggery-sweeteners', 'Pure organic jaggery, palm jaggery, honey, and natural sweeteners from Konkan', '/images/categories/jaggery.jpg', NULL, 1, 9, 'Organic Jaggery & Natural Sweeteners Online | Konkan Bazaar', 'Pure organic jaggery, palm jaggery, and natural sweeteners from Konkan farms'),
(10, 'Traditional Snacks', 'traditional-snacks', 'Traditional Konkan snacks including chakli, murukku, poha, and festive treats', '/images/categories/snacks.jpg', NULL, 1, 10, 'Traditional Konkan Snacks Online | Konkan Bazaar', 'Authentic Konkan snacks and traditional festive treats made with traditional recipes'),
(11, 'Handmade Crafts', 'handmade-crafts', 'Handcrafted Konkan souvenirs, decor, and traditional items', '/images/categories/crafts.jpg', NULL, 1, 11, 'Handmade Konkan Crafts Online | Konkan Bazaar', 'Authentic handcrafted Konkan souvenirs, home decor, and traditional items'),
(12, 'Monsoon Specials', 'monsoon-specials', 'Special Konkan monsoon products including dried fish, bhajji mixes, and seasonal treats', '/images/categories/monsoon.jpg', NULL, 1, 12, 'Konkan Monsoon Specials Online | Konkan Bazaar', 'Special monsoon products from Konkan - traditional snacks, dried fish, and seasonal treats');

-- ============================================================
-- SUB-CATEGORIES (second level)
-- ============================================================
INSERT INTO categories (name, slug, description, image_url, parent_id, is_active, sort_order) VALUES
('Alphonso Mangoes', 'alphonso-mangoes', 'Premium Devgad and Ratnagiri Alphonso mangoes', '/images/categories/alphonso.jpg', 1, 1, 1),
('Payri & Local Mangoes', 'payri-local-mangoes', 'Traditional Konkan local mango varieties like Payri, Mankurad, and others', '/images/categories/payri.jpg', 1, 1, 2),
('Dried Fish', 'dried-fish', 'Traditional Konkan style dried fish varieties', '/images/categories/dried-fish.jpg', 2, 1, 1),
('Fresh Seafood', 'fresh-seafood', 'Fresh Konkan coast seafood including prawns, crabs, and fish', '/images/categories/fresh-seafood.jpg', 2, 1, 2),
('Coconut Oil', 'coconut-oil', 'Pure cold-pressed coconut oil from Konkan coconuts', '/images/categories/coconut-oil.jpg', 3, 1, 1),
('Indrayani Rice', 'indrayani-rice', 'Premium Indrayani rice from Konkan region', '/images/categories/indrayani.jpg', 4, 1, 1),
('Ambemohar Rice', 'ambemohar-rice', 'Fragrant Ambemohar rice from the Sahyadri foothills', '/images/categories/ambemohar.jpg', 4, 1, 2),
('Kokum Products', 'kokum-products', 'Pure Kokum juice, concentrate, and dried kokum', '/images/categories/kokum-products.jpg', 5, 1, 1),
('Cashew Nuts', 'cashew-nuts', 'Premium Konkan cashew nuts in various preparations', '/images/categories/cashew-nuts.jpg', 7, 1, 1),
('Black Pepper', 'black-pepper', 'Pure organic black pepper from Konkan region', '/images/categories/black-pepper.jpg', 8, 1, 1),
('Coconut Jaggery', 'coconut-jaggery', 'Pure organic coconut jaggery from Konkan farms', '/images/categories/coconut-jaggery.jpg', 9, 1, 1),
('Konkan Crafts', 'konkan-crafts', 'Handcrafted Konkan souvenirs and decor items', '/images/categories/konkan-crafts.jpg', 11, 1, 1);

-- ============================================================
-- DUMMY USERS (passwords are hashed versions of "password123")
-- ============================================================
INSERT INTO users (id, name, email, password_hash, phone, role, is_verified, is_active) VALUES
(1, 'Admin Konkan', 'admin@konkanbazaar.in', '$2a$12$vzI6l93uscJAlFLigkhIOuE1zhhlaWgAPgH2VZ19ZNtxaybiM./F6', '9876543210', 'admin', 1, 1),
(2, 'Ramesh Gaonkar', 'ramesh@example.com', '$2a$12$LJ3m4ys3Lg3YOCwH3YOCwH3YOCwH3YOCwH3YOCwHeJ3m4ys3Lg3Yo', '9876543211', 'customer', 1, 1),
(3, 'Priya Tendulkar', 'priya@example.com', '$2a$12$LJ3m4ys3Lg3YOCwH3YOCwH3YOCwH3YOCwH3YOCwHeJ3m4ys3Lg3Yo', '9876543212', 'customer', 1, 1),
(4, 'Sahil Naik', 'sahil@example.com', '$2a$12$LJ3m4ys3Lg3YOCwH3YOCwH3YOCwH3YOCwH3YOCwHeJ3m4ys3Lg3Yo', '9876543213', 'seller', 1, 1),
(5, 'Anita Desai', 'anita@example.com', '$2a$12$LJ3m4ys3Lg3YOCwH3YOCwH3YOCwH3YOCwH3YOCwHeJ3m4ys3Lg3Yo', '9876543214', 'customer', 1, 1);

-- ============================================================
-- PRODUCTS — 200 Konkan Region Products
-- ============================================================

-- === CATEGORY 1: MANGOES & FRUITS (Products 1-25) ===
-- Sub-category 13: Alphonso Mangoes (1-12)
INSERT INTO products (id, name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
(1, 'Devgad Alphonso Mango - Premium Box (12 pcs)', 'devgad-alphonso-mango-premium-box-12-pcs', 'Handpicked Devgad Alphonso mangoes from the famous Devgad region of Sindhudurg district. These golden-yellow mangoes are known for their unparalleled sweetness, rich aroma, and buttery texture. Each mango is carefully selected at the perfect ripeness and packed in a traditional mango box for gifting.', 'Premium Devgad Alphonso mangoes - 12 handpicked pieces in gift box', 1899.00, 2499.00, 200, 'MAN-ALP-001', 1, 'Konkan Bazaar Select', 3000, 'box', 1, 1, 1, 1, 'Devgad, Sindhudurg', 7, 'Fresh Alphonso Mangoes', '{"calories": 150, "serving_size": "100g", "vitamin_c": "37mg", "vitamin_a": "54mcg", "fiber": "1.6g", "sugar": "14.8g"}', 'Store at room temperature. Once ripe, refrigerate and consume within 2-3 days.', 4.80, 128, 1500, 25000),
(2, 'Ratnagiri Alphonso Mango - Family Pack (6 pcs)', 'ratnagiri-alphonso-mango-family-pack-6-pcs', 'Premium Ratnagiri Alphonso mangoes sourced directly from the orchards of Ratnagiri district. Known as the King of Mangoes, these have a distinct sweet taste with hints of saffron and honey. Perfect for desserts, smoothies, or eating fresh.', 'Premium Ratnagiri Alphonso mangoes - 6 large pieces', 999.00, 1299.00, 300, 'MAN-ALP-002', 1, 'Konkan Bazaar Select', 1800, 'pack', 1, 1, 1, 1, 'Ratnagiri', 7, 'Fresh Alphonso Mangoes', '{"calories": 150, "serving_size": "100g", "vitamin_c": "37mg", "vitamin_a": "54mcg", "fiber": "1.6g", "sugar": "14.8g"}', 'Store at room temperature. Refrigerate after ripening.', 4.70, 95, 1200, 18000),
(3, 'Devgad Hapus Mango Pulp (1kg)', 'devgad-hapus-mango-pulp-1kg', 'Pure Devgad Hapus mango pulp made from handpicked, fully ripened Alphonso mangoes. No added sugar, no preservatives, no artificial colors. The rich golden pulp captures the authentic taste of Konkan mangoes, perfect for making mango shakes, desserts, and smoothies all year round.', 'Pure Devgad Alphonso mango pulp - No preservatives, No added sugar', 599.00, 799.00, 500, 'MAN-PLP-001', 1, 'Konkan Delight', 1000, 'jar', 1, 1, 1, 1, 'Devgad, Sindhudurg', 365, 'Pure Alphonso Mango Pulp', '{"calories": 120, "serving_size": "100g", "sugar": "28g", "fiber": "0.5g", "vitamin_c": "25mg"}', 'Store in cool dry place. Refrigerate after opening and consume within 7 days.', 4.60, 200, 3000, 35000),
(4, 'Alphonso Mango Gift Hamper (Premium)', 'alphonso-mango-gift-hamper-premium', 'Luxury gift hamper containing 12 premium Devgad Alphonso mangoes, 250g premium cashews, 200g mango pulp, and a traditional Konban handwoven basket. Perfect Diwali or festival gifting.', 'Luxury mango gift hamper with cashews, pulp, and handwoven basket', 2999.00, 3999.00, 100, 'MAN-GFT-001', 1, 'Konkan Bazaar Select', 5000, 'hamper', 0, 1, 1, 0, 'Devgad & Ratnagiri', 10, 'Alphonso Mangoes, Cashews, Mango Pulp', '{"calories": 200, "serving_size": "250g", "includes": "12 mangoes, 250g cashews, 200g pulp"}', 'Gift box - handle with care. Mangoes at room temperature.', 4.90, 45, 350, 8000),
(5, 'Payri Mango (1 Dozen)', 'payri-mango-1-dozen', 'Traditional Payri mangoes from the farms of Sindhudurg. These small to medium-sized mangoes have a unique sweet-tangy flavor profile that mango connoisseurs love. The skin is greenish-yellow with a distinct red blush. Known for their fibrous texture and intense mango aroma.', 'Traditional Payri mangoes - 12 pieces with unique sweet-tangy flavor', 699.00, 899.00, 250, 'MAN-PAY-001', 1, 'Konkan Heritage', 2400, 'dozen', 0, 0, 1, 1, 'Sindhudurg', 5, 'Fresh Payri Mangoes', '{"calories": 140, "serving_size": "100g", "vitamin_c": "30mg", "fiber": "2.0g", "sugar": "13g"}', 'Store at room temperature. Use within 3-5 days of ripening.', 4.30, 65, 800, 12000),
(6, 'Mankurad Mango (1 Dozen)', 'mankurad-mango-1-dozen', 'Premium Mankurad mangoes from Goa, known for their distinct sweet taste with a hint of spice. These medium-sized mangoes have smooth, yellow skin and deep orange, non-fibrous flesh. Highly prized in Goa for making mango desserts and eaten fresh.', 'Premium Goan Mankurad mangoes - 12 pieces, non-fibrous flesh', 849.00, 1099.00, 180, 'MAN-MAN-001', 1, 'Goan Heritage', 2400, 'dozen', 1, 0, 1, 0, 'Goa', 5, 'Fresh Mankurad Mangoes', '{"calories": 145, "serving_size": "100g", "vitamin_c": "35mg", "vitamin_a": "50mcg", "fiber": "1.2g"}', 'Store at room temperature away from direct sunlight.', 4.50, 55, 600, 9000),
(7, 'Kesar Mango (1 Dozen)', 'kesar-mango-1-dozen', 'Sweet and aromatic Kesar mangoes grown in the Konkan belt. Known for their distinct saffron-colored flesh and sweet taste. Perfect for making mango lassi, desserts, or eating fresh.', 'Sweet Kesar mangoes - 12 pieces, saffron-colored sweet flesh', 799.00, 999.00, 200, 'MAN-KES-001', 1, 'Konkan Delight', 2400, 'dozen', 0, 0, 1, 0, 'Ratnagiri', 5, 'Fresh Kesar Mangoes', '{"calories": 148, "serving_size": "100g", "vitamin_c": "32mg", "vitamin_a": "52mcg"}', 'Store at room temperature.', 4.40, 42, 500, 7000),
(8, 'Dried Mango Slices (500g)', 'dried-mango-slices-500g', 'Sun-dried Alphonso mango slices, naturally sweetened by the Konkan sun. No added sugar or preservatives. A healthy, chewy snack that retains the authentic taste of Konkan mangoes. Perfect for snacking or adding to desserts.', 'Natural sun-dried Alphonso mango slices - No added sugar', 349.00, 449.00, 400, 'MAN-DRY-001', 1, 'Konkan Bazaar Select', 500, 'pack', 0, 1, 0, 1, 'Devgad, Sindhudurg', 180, 'Dried Alphonso Mango Slices', '{"calories": 320, "serving_size": "100g", "sugar": "65g", "fiber": "3g", "carbohydrates": "78g"}', 'Store in airtight container in cool dry place.', 4.30, 35, 450, 5500),
(9, 'Raw Green Mango (1kg)', 'raw-green-mango-1kg', 'Fresh, firm raw green mangoes from Konkan farms. Perfect for making pickles, chutneys, and traditional Konkan cuisine. Sourced directly from local farmers for optimal freshness.', 'Fresh raw green mangoes for pickles and chutneys - 1kg', 199.00, 249.00, 500, 'MAN-RAW-001', 1, 'Konkan Fresh', 1000, 'kg', 0, 0, 1, 1, 'Sindhudurg', 10, 'Raw Green Mangoes', '{"calories": 60, "serving_size": "100g", "vitamin_c": "40mg", "fiber": "1.8g"}', 'Store in cool place. Refrigerate for longer shelf life.', 4.10, 28, 700, 6000),
(10, 'Totapuri Mango (1kg)', 'totapuri-mango-1kg', 'Totapuri mangoes, also known as Bangalore Mango, grown in the Konkan region. These long-shaped mangoes have a distinct tangy-sweet flavor. Excellent for making mango juice, pulp, and cooking.', 'Tangy-sweet Totapuri mangoes - 1kg for cooking and juice', 249.00, 299.00, 350, 'MAN-TOT-001', 1, 'Konkan Fresh', 1000, 'kg', 0, 0, 0, 0, 'Ratnagiri', 7, 'Fresh Totapuri Mangoes', '{"calories": 140, "serving_size": "100g", "vitamin_c": "35mg"}', 'Store at room temperature.', 4.00, 18, 350, 3500),
(11, 'Mango Squash Concentrate (750ml)', 'mango-squash-concentrate-750ml', 'Premium mango squash concentrate made from Alphonso mangoes. Just mix with water or milk for an instant refreshing drink. No artificial flavors or colors.', 'Alphonso mango squash concentrate - Makes 3L of drink', 249.00, 299.00, 600, 'MAN-SQU-001', 1, 'Konkan Delight', 750, 'bottle', 0, 0, 0, 0, 'Ratnagiri', 365, 'Mango Pulp, Sugar, Citric Acid, Preservatives (as permitted)', '{"calories": 90, "serving_size": "30ml", "sugar": "20g"}', 'Store in cool dry place. Refrigerate after opening.', 4.20, 30, 600, 4000),
(12, 'Organic Kokum Fruit (500g)', 'organic-kokum-fruit-500g', 'Dried organic kokum fruit (Garcinia indica) from the forests of Konkan. Used in traditional Konkan cuisine for making Sol Kadhi, as a natural souring agent in curries, and for its digestive and cooling properties.', 'Organic dried kokum fruit - Traditional Konkan superfood', 299.00, 379.00, 500, 'KOK-001', 1, 'Konkan Heritage', 500, 'pack', 1, 0, 0, 1, 'Sindhudurg', 365, 'Dried Kokum Fruit (Garcinia indica)', '{"calories": 45, "serving_size": "10g", "vitamin_c": "15mg", "fiber": "1g", "antioxidants": "High"}', 'Store in airtight container in cool dry place away from moisture.', 4.50, 80, 1200, 10000);

-- More Mango Products (13-25)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Mango Jam - Alphonso (500g)', 'mango-jam-alphonso-500g', 'Homestyle Alphonso mango jam made with real Alphonso mango pulp and minimal sugar. No artificial flavors or preservatives. Spreads beautifully on toast, parathas, or use as dessert topping.', 'Homestyle Alphonso mango jam - No artificial flavors', 199.00, 249.00, 400, 'MAN-JAM-001', 1, 'Konkan Delight', 500, 'jar', 0, 0, 0, 0, 'Devgad', 180, 'Alphonso Mango Pulp, Sugar, Pectin, Lemon Juice', '{"calories": 50, "serving_size": "20g", "sugar": "12g"}', 'Refrigerate after opening.', 4.30, 22, 400, 3000),
('Raw Mango Powder (Amchur) 200g', 'raw-mango-powder-amchur-200g', 'Pure raw mango powder made from sun-dried raw green mangoes from Konkan farms. A tangy spice essential for Indian cooking, chaats, and marinades.', 'Pure Amchur powder from Konkan raw mangoes', 129.00, 159.00, 600, 'MAN-AMC-001', 1, 'Konkan Heritage', 200, 'pack', 0, 0, 0, 1, 'Ratnagiri', 540, 'Dried Raw Mango Powder', '{"calories": 15, "serving_size": "5g", "vitamin_c": "2mg"}', 'Store in airtight container in cool dry place.', 4.10, 15, 300, 2200),
('Banana - Rajeli (1 Dozen)', 'banana-rajeli-1-dozen', 'Traditional Rajeli bananas from the Konkan region, known for their sweet taste and soft texture. Smaller than regular bananas but packed with flavor.', 'Traditional Konkan Rajeli bananas - 12 pieces', 149.00, 179.00, 300, 'FRT-BAN-001', 1, 'Konkan Fresh', 1500, 'dozen', 0, 0, 0, 1, 'Sindhudurg', 5, 'Fresh Rajeli Bananas', '{"calories": 105, "serving_size": "100g", "potassium": "358mg", "fiber": "3.1g"}', 'Store at room temperature.', 4.20, 12, 500, 3000),
('Custard Apple - Sitaphal (6 pcs)', 'custard-apple-sitaphal-6-pcs', 'Fresh custard apples (Sitaphal) from the Konkan region. These naturally sweet, creamy fruits are rich in antioxidants and vitamin C. Handpicked at peak ripeness.', 'Fresh Konkan Sitaphal - 6 pieces, naturally sweet', 349.00, 449.00, 150, 'FRT-SIT-001', 1, 'Konkan Fresh', 1200, 'pack', 0, 0, 1, 0, 'Ratnagiri', 4, 'Fresh Custard Apples', '{"calories": 101, "serving_size": "100g", "vitamin_c": "19mg", "fiber": "2.4g", "potassium": "382mg"}', 'Store at room temperature. Refrigerate once fully ripe.', 4.50, 20, 250, 4000),
('Fresh Tender Coconut (5 pcs)', 'fresh-tender-coconut-5-pcs', 'Fresh tender coconuts (Dabi) from the Konkan coast. Each coconut is full of refreshing coconut water and soft, delicious malai (coconut meat). Perfect for a natural, hydrating drink on hot days.', 'Fresh Konkan tender coconuts - 5 pieces with water and malai', 399.00, 499.00, 200, 'FRT-COC-001', 1, 'Konkan Fresh', 5000, 'pack', 0, 1, 0, 1, 'Goa', 7, 'Fresh Tender Coconuts', '{"calories": 45, "serving_size": "1 coconut water", "electrolytes": "Natural", "potassium": "600mg"}', 'Store in cool place. Consume within 7 days. Best refrigerated.', 4.60, 45, 800, 8000),
('Coconut Water - Packaged (1L)', 'coconut-water-packaged-1l', 'Pure natural coconut water sourced from young Konkan coconuts. No added sugar, no preservatives, no artificial flavors. A refreshing, electrolyte-rich natural beverage.', 'Pure Konkan coconut water - No added sugar, 1L pack', 99.00, 129.00, 800, 'FRT-COW-001', 1, 'Konkan Bazaar Select', 1000, 'carton', 0, 0, 0, 1, 'Goa', 180, 'Pure Coconut Water', '{"calories": 46, "serving_size": "240ml", "potassium": "600mg", "sodium": "250mg", "magnesium": "60mg"}', 'Store in cool dry place. Refrigerate after opening and consume within 24 hours.', 4.00, 18, 900, 4500),
('Fresh Watermelon (1 pc)', 'fresh-watermelon-1-pc', 'Fresh, juicy watermelons grown in the Konkan region. Perfectly sweet and hydrating. Ideal for summer fruit salads, juices, and desserts.', 'Fresh Konkan watermelon - Sweet and juicy', 149.00, 199.00, 100, 'FRT-WAT-001', 1, 'Konkan Fresh', 5000, 'piece', 0, 0, 0, 0, 'Sindhudurg', 10, 'Fresh Watermelon', '{"calories": 30, "serving_size": "100g", "vitamin_c": "8mg", "vitamin_a": "28mcg"}', 'Store in cool place. Refrigerate after cutting.', 3.90, 8, 300, 2000),
('Fresh Papaya - Madhu Bindu (1 pc)', 'fresh-papaya-madhu-bindu-1-pc', 'Madhu Bindu variety papaya from Konkan farms. Known for its exceptional sweetness and rich orange flesh. Rich in papain enzyme and vitamin C.', 'Sweet Madhu Bindu papaya - Rich in vitamin C', 99.00, 129.00, 150, 'FRT-PAP-001', 1, 'Konkan Fresh', 2000, 'piece', 0, 0, 0, 1, 'Ratnagiri', 7, 'Fresh Papaya', '{"calories": 43, "serving_size": "100g", "vitamin_c": "62mg", "fiber": "1.7g"}', 'Store at room temperature. Refrigerate once ripe.', 4.10, 10, 200, 1800),
('Fresh Pineapple (1 pc)', 'fresh-pineapple-1-pc', 'Sweet and tangy pineapples grown in the Konkan region. Golden yellow flesh with perfect sweetness. Great for fruit salads, desserts, or fresh juice.', 'Sweet Konkan pineapple - Golden and juicy', 89.00, 119.00, 200, 'FRT-PIN-001', 1, 'Konkan Fresh', 1500, 'piece', 0, 0, 0, 0, 'Goa', 7, 'Fresh Pineapple', '{"calories": 50, "serving_size": "100g", "vitamin_c": "48mg", "manganese": "0.9mg"}', 'Store at room temperature. Refrigerate after cutting.', 4.00, 12, 350, 2500),
('Dried Fig - Anjeer (500g)', 'dried-fig-anjeer-500g', 'Premium dried figs from the Konkan region. Naturally sun-dried, no added sugar. Rich in fiber, calcium, and antioxidants. Perfect healthy snack.', 'Natural dried Konkan figs - No added sugar', 399.00, 499.00, 300, 'FRT-FIG-001', 1, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 1, 'Sindhudurg', 365, 'Dried Figs (Ficus carica)', '{"calories": 249, "serving_size": "100g", "fiber": "9.8g", "calcium": "162mg", "iron": "2mg"}', 'Store in airtight container in cool dry place.', 4.30, 15, 200, 2800),
('Organic Jamun Fruit (500g)', 'organic-jamun-fruit-500g', 'Fresh organic Jamun (Java Plum) fruits from the Konkan region. These purple-black fruits are known for their unique sweet-tart flavor and health benefits. Rich in iron, vitamin C, and antioxidants.', 'Organic fresh Jamun fruit - Rich in iron and antioxidants', 249.00, 299.00, 100, 'FRT-JAM-001', 1, 'Konkan Heritage', 500, 'pack', 0, 0, 1, 1, 'Ratnagiri', 3, 'Fresh Jamun Fruits', '{"calories": 62, "serving_size": "100g", "vitamin_c": "18mg", "iron": "1.4mg", "antioxidants": "High"}', 'Store in refrigerator. Consume within 2-3 days.', 4.40, 18, 180, 3200);

-- === CATEGORY 2: COASTAL SEAFOOD (Products 26-50) ===
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Sundried Bombay Duck - Bombil (500g)', 'sundried-bombay-duck-bombil-500g', 'Premium sundried Bombay Duck (Bombil) from the coastal villages of Ratnagiri. Traditional sun-drying process preserves the authentic flavor. A coastal delicacy, perfect for frying or adding to curries.', 'Traditional sundried Bombil - Coastal Konkan delicacy', 449.00, 549.00, 200, 'SFD-BOM-001', 2, 'Konkan Heritage', 500, 'pack', 1, 1, 0, 0, 'Ratnagiri', 180, 'Dried Bombay Duck Fish, Salt', '{"calories": 250, "serving_size": "100g", "protein": "50g", "fat": "5g", "omega_3": "2.5g"}', 'Store in airtight container in cool dry place. No refrigeration needed.', 4.60, 90, 2000, 22000),
('Sundried Prawns - Sungta (500g)', 'sundried-prawns-sungta-500g', 'Traditional sundried prawns (Sungta) from the Konkan coast. Medium-sized prawns dried using age-old coastal techniques. Intense seafood flavor perfect for Konkan curries and stir-fries.', 'Traditional sundried prawns - Authentic Konkan Sungta', 599.00, 749.00, 150, 'SFD-PRW-001', 2, 'Konkan Heritage', 500, 'pack', 1, 1, 0, 0, 'Sindhudurg', 180, 'Dried Prawns, Salt', '{"calories": 280, "serving_size": "100g", "protein": "55g", "fat": "6g", "calcium": "150mg"}', 'Store in airtight container. Keep away from moisture.', 4.50, 65, 1500, 16000),
('Sundried Mackerel - Bangda (500g)', 'sundried-mackerel-bangda-500g', 'Sundried mackerel (Bangda) prepared in traditional Konkan style using fresh catch from the Arabian Sea. Rich in omega-3 fatty acids and intense coastal flavor.', 'Traditional sundried Bangda mackerel - Omega-3 rich', 349.00, 449.00, 180, 'SFD-MAC-001', 2, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 0, 'Goa', 180, 'Dried Mackerel, Salt', '{"calories": 260, "serving_size": "100g", "protein": "48g", "omega_3": "3g", "vitamin_d": "20mcg"}', 'Store in cool dry place in airtight container.', 4.30, 35, 800, 9000),
('Sundried Shrimp - Kolambi (250g)', 'sundried-shrimp-kolambi-250g', 'Small sundried shrimp (Kolambi) from Konkan coast. These tiny flavor bombs are essential Konkan pantry items. Used in Konkan-style chutneys, curries, and rice dishes.', 'Traditional sundried small shrimp - Kolambi, 250g', 299.00, 379.00, 300, 'SFD-SHR-001', 2, 'Konkan Heritage', 250, 'pack', 0, 1, 0, 0, 'Ratnagiri', 180, 'Dried Small Shrimp, Salt', '{"calories": 240, "serving_size": "100g", "protein": "50g", "calcium": "200mg"}', 'Store in airtight container in cool dry place.', 4.40, 40, 900, 8500),
('Fresh King Prawns - Raw (500g)', 'fresh-king-prawns-raw-500g', 'Fresh large King Prawns (Kolambi) caught from the Arabian Sea off the Konkan coast. Cleaned, deveined, and flash-frozen for freshness. Perfect for tandoori, curry, or garlic butter preparation.', 'Fresh King Prawns - Large size, cleaned, 500g', 799.00, 999.00, 80, 'SFD-KPR-001', 2, 'Konkan Fresh', 500, 'pack', 1, 0, 0, 0, 'Goa', 30, 'Fresh King Prawns', '{"calories": 120, "serving_size": "100g", "protein": "24g", "fat": "1.5g", "cholesterol": "180mg", "omega_3": "1.8g"}', 'Keep frozen. Thaw in refrigerator before cooking.', 4.60, 38, 600, 7500),
('Fresh Pomfret - Whole (2 pcs)', 'fresh-pomfret-whole-2-pcs', 'Fresh whole Pomfret (Paplet) from Konkan waters. Known for its delicate white flesh and mild sweet flavor. Perfect for Konkan-style fish curry, frying, or steaming.', 'Fresh Pomfret - 2 whole pieces, mild sweet flavor', 599.00, 749.00, 60, 'SFD-POM-001', 2, 'Konkan Fresh', 1000, 'pack', 1, 0, 0, 0, 'Ratnagiri', 3, 'Fresh Pomfret Fish', '{"calories": 110, "serving_size": "100g", "protein": "20g", "fat": "3g", "omega_3": "1.5g"}', 'Keep refrigerated. Cook within 24-48 hours.', 4.50, 30, 450, 6500),
('Fresh Bangda Mackerel (500g)', 'fresh-bangda-mackerel-500g', 'Fresh Indian Mackerel (Bangda) from the Arabian Sea. Rich, flavorful fish perfect for Konkan curries and fried preparations. Known for its high omega-3 content.', 'Fresh Bangda Mackerel - 500g, rich in omega-3', 249.00, 299.00, 100, 'SFD-BNG-001', 2, 'Konkan Fresh', 500, 'pack', 0, 1, 0, 0, 'Sindhudurg', 3, 'Fresh Indian Mackerel', '{"calories": 160, "serving_size": "100g", "protein": "19g", "fat": "9g", "omega_3": "2.6g"}', 'Keep refrigerated. Cook within 24 hours.', 4.30, 25, 800, 5500),
('Fresh Surmai - Kingfish Steaks (500g)', 'fresh-surmai-kingfish-steaks-500g', 'Fresh Kingfish (Surmai) steaks from the Konkan coast. Firm, meaty flesh that holds up well in curries and grilling. A favorite in Goan and Malvani cuisine.', 'Fresh Surmai Kingfish steaks - 500g, firm meaty flesh', 649.00, 799.00, 70, 'SFD-SUR-001', 2, 'Konkan Fresh', 500, 'pack', 0, 0, 0, 0, 'Goa', 3, 'Fresh Kingfish Steaks', '{"calories": 130, "serving_size": "100g", "protein": "22g", "fat": "4g", "omega_3": "2g"}', 'Keep refrigerated. Cook within 24 hours.', 4.40, 20, 300, 4500),
('Fish Curry Masala - Malvani (200g)', 'fish-curry-masala-malvani-200g', 'Authentic Malvani fish curry masala blend made with traditional Konkan spices. No artificial flavors or colors. Just add coconut milk and fresh fish for an authentic Konkan fish curry.', 'Authentic Malvani fish curry masala - 200g pack', 129.00, 159.00, 500, 'SFD-MAS-001', 2, 'Konkan Heritage', 200, 'pack', 0, 1, 0, 1, 'Ratnagiri', 540, 'Red Chili, Coriander, Cumin, Pepper, Turmeric, Garlic, Onion, Coconut, Tamarind', '{"calories": 25, "serving_size": "10g"}', 'Store in airtight container in cool dry place.', 4.50, 55, 1500, 8000),
('Prawn Pickle - Kolambi Lonche (400g)', 'prawn-pickle-kolambi-lonche-400g', 'Traditional Konkan style prawn pickle made with sundried prawns and authentic spices. A coastal delicacy that pairs perfectly with steamed rice and dal.', 'Traditional Konkan prawn pickle - Kolambi Lonche', 249.00, 299.00, 250, 'SFD-PPK-001', 2, 'Konkan Heritage', 400, 'jar', 0, 0, 0, 0, 'Sindhudurg', 365, 'Dried Prawns, Mustard Oil, Red Chili, Turmeric, Garlic, Salt, Vinegar', '{"calories": 60, "serving_size": "20g", "protein": "4g"}', 'Store in cool dry place. Refrigerate after opening.', 4.40, 28, 600, 4500),
('Bangda Fry Masala (100g)', 'bangda-fry-masala-100g', 'Special spice blend for Konkan-style Bangda (Mackerel) fry. Made with traditional Konkan spices and grated coconut. Gives an authentic coastal flavor to fried fish.', 'Special Bangda fry masala mix - 100g', 79.00, 99.00, 600, 'SFD-BFM-001', 2, 'Konkan Heritage', 100, 'pack', 0, 0, 0, 0, 'Ratnagiri', 365, 'Red Chili, Coriander, Cumin, Turmeric, Garlic, Ginger, Coconut', '{"calories": 20, "serving_size": "10g"}', 'Store in cool dry place.', 4.10, 15, 400, 2500),
('Dried Anchovies - Kati (250g)', 'dried-anchovies-kati-250g', 'Traditional sundried anchovies (Kati) from the Konkan coast. Small, intensely flavorful dried fish used in Konkan chutneys, curries, and as a side dish with rice.', 'Traditional sundried anchovies - Kati, 250g', 199.00, 249.00, 350, 'SFD-ANC-001', 2, 'Konkan Heritage', 250, 'pack', 0, 0, 0, 0, 'Goa', 180, 'Dried Anchovies, Salt', '{"calories": 220, "serving_size": "100g", "protein": "45g", "calcium": "350mg"}', 'Store in airtight container in cool dry place.', 4.20, 20, 500, 3500),
('Goan Recheado Masala Paste (250g)', 'goan-recheado-masala-paste-250g', 'Authentic Goan Recheado masala paste made with traditional Goan spices, red chilies, vinegar, and garlic. Perfect for stuffing mackerel, pomfret, or prawns before frying.', 'Authentic Goan Recheado masala - 250g, for stuffed fish', 149.00, 189.00, 400, 'SFD-REC-001', 2, 'Goan Heritage', 250, 'jar', 0, 0, 0, 0, 'Goa', 180, 'Red Chili, Garlic, Cumin, Pepper, Cloves, Cinnamon, Vinegar, Salt', '{"calories": 30, "serving_size": "15g"}', 'Refrigerate after opening.', 4.50, 32, 700, 5000);

-- === CATEGORY 3: COCONUT PRODUCTS (Products 51-65) ===
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Cold Pressed Coconut Oil (1L)', 'cold-pressed-coconut-oil-1l', 'Pure cold-pressed virgin coconut oil made from fresh Konkan coconuts. No heat processing, no chemicals, no preservatives. Retains the natural aroma, flavor, and nutrients of fresh coconut. Perfect for cooking, hair care, and skin care.', 'Pure cold-pressed virgin coconut oil - 1L, no chemicals', 449.00, 549.00, 400, 'COC-OIL-001', 3, 'Konkan Heritage', 1000, 'bottle', 1, 1, 0, 1, 'Sindhudurg', 540, '100% Cold Pressed Virgin Coconut Oil', '{"calories": 120, "serving_size": "15ml", "fat": "14g", "saturated_fat": "12g"}', 'Store in cool dry place away from direct sunlight. Solidifies in winter - natural.', 4.70, 150, 3000, 30000),
('Virgin Coconut Oil - Organic (500ml)', 'virgin-coconut-oil-organic-500ml', 'Organic certified virgin coconut oil extracted from fresh organic coconuts grown in Konkan. Cold-pressed and unrefined. Rich in medium-chain triglycerides (MCTs) and lauric acid.', 'Organic virgin coconut oil - Cold pressed, 500ml', 299.00, 379.00, 500, 'COC-OIL-002', 3, 'Konkan Bazaar Select', 500, 'bottle', 1, 1, 0, 1, 'Ratnagiri', 540, '100% Organic Virgin Coconut Oil', '{"calories": 120, "serving_size": "15ml", "mct": "6g", "lauric_acid": "5g"}', 'Store in cool dark place. Natural coconut aroma may vary.', 4.60, 85, 2500, 22000),
('Desiccated Coconut Powder (500g)', 'desiccated-coconut-powder-500g', 'Fine desiccated coconut powder made from fresh, mature Konkan coconuts. Dried using gentle heat to preserve natural flavor and nutrients. Perfect for cooking, baking, and traditional Konkan recipes.', 'Fine desiccated coconut powder - 500g, natural', 199.00, 249.00, 600, 'COC-DES-001', 3, 'Konkan Fresh', 500, 'pack', 0, 0, 0, 0, 'Goa', 365, '100% Desiccated Coconut', '{"calories": 135, "serving_size": "30g", "fiber": "5g", "fat": "12g"}', 'Store in airtight container in cool dry place.', 4.20, 30, 800, 5000),
('Coconut Milk - Fresh (500ml)', 'coconut-milk-fresh-500ml', 'Fresh coconut milk extracted from mature Konkan coconuts. Rich and creamy with no added preservatives. Essential for authentic Konkan curries, sol kadhi, and desserts.', 'Fresh creamy coconut milk - 500ml, no preservatives', 149.00, 179.00, 300, 'COC-MLK-001', 3, 'Konkan Fresh', 500, 'carton', 0, 1, 0, 0, 'Sindhudurg', 7, 'Fresh Coconut Milk, Water, Citric Acid', '{"calories": 45, "serving_size": "30ml", "fat": "4.5g"}', 'Refrigerate. Shake well before use. Consume within 5 days of opening.', 4.30, 25, 900, 4200),
('Coconut Cream - Thick (200ml)', 'coconut-cream-thick-200ml', 'Thick coconut cream extracted from the first pressing of fresh Konkan coconuts. Extra rich and creamy. Perfect for rich curries, desserts, and making coconut-based sauces.', 'Thick coconut cream - 200ml, first pressing', 129.00, 159.00, 400, 'COC-CRM-001', 3, 'Konkan Fresh', 200, 'carton', 0, 0, 0, 0, 'Goa', 10, 'Fresh Coconut Cream', '{"calories": 55, "serving_size": "30ml", "fat": "5.5g"}', 'Refrigerate. Consume within 5 days of opening.', 4.10, 15, 400, 2800),
('Dry Coconut - Copra (500g)', 'dry-coconut-copra-500g', 'Sun-dried coconut pieces (Copra) from mature Konkan coconuts. Used in traditional Konkan cooking for making chutneys, curries, and sweets. Also used for extracting coconut oil.', 'Sun-dried coconut pieces - Copra, 500g', 249.00, 299.00, 500, 'COC-COP-001', 3, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 0, 'Ratnagiri', 365, 'Dried Coconut Pieces', '{"calories": 140, "serving_size": "30g", "fiber": "4g", "fat": "13g"}', 'Store in airtight container in cool dry place.', 4.00, 10, 300, 2500),
('Coconut Chips - Roasted (200g)', 'coconut-chips-roasted-200g', 'Roasted coconut chips made from fresh Konkan coconuts. Lightly salted and roasted to golden perfection. A healthy, crunchy snack rich in fiber and healthy fats.', 'Roasted coconut chips - 200g, healthy crunchy snack', 149.00, 189.00, 400, 'COC-CHP-001', 3, 'Konkan Bazaar Select', 200, 'pack', 0, 0, 0, 0, 'Goa', 120, 'Fresh Coconut, Salt', '{"calories": 180, "serving_size": "30g", "fiber": "5g", "fat": "16g"}', 'Store in airtight container in cool dry place.', 4.30, 18, 500, 3200),
('Coconut Vinegar (500ml)', 'coconut-vinegar-500ml', 'Natural coconut vinegar made from fermented coconut sap. Mild and fruity with less acidity than regular vinegar. Used in Konkan cuisine for pickling and marinades.', 'Natural coconut vinegar - 500ml, mild and fruity', 129.00, 159.00, 300, 'COC-VIN-001', 3, 'Konkan Heritage', 500, 'bottle', 0, 0, 0, 1, 'Sindhudurg', 730, 'Fermented Coconut Sap', '{"calories": 5, "serving_size": "15ml"}', 'Store in cool dry place away from direct sunlight.', 4.00, 10, 200, 1500),
('Coconut Sugar - Organic (500g)', 'coconut-sugar-organic-500g', 'Organic coconut sugar made from the sap of Konkan coconut palm flowers. Low glycemic index, rich in minerals, and a natural alternative to refined sugar. Caramel-like flavor.', 'Organic coconut sugar - 500g, low glycemic', 299.00, 379.00, 350, 'COC-SGR-001', 3, 'Konkan Bazaar Select', 500, 'pack', 0, 0, 0, 1, 'Goa', 540, '100% Organic Coconut Sugar', '{"calories": 45, "serving_size": "10g", "glycemic_index": "35", "potassium": "130mg"}', 'Store in airtight container in cool dry place.', 4.20, 15, 350, 2800),
('Coconut Laddu (200g)', 'coconut-laddu-200g', 'Traditional Konkan-style coconut laddus made with fresh grated coconut and pure jaggery. No preservatives, no artificial flavors. A beloved festive sweet from the Konkan region.', 'Traditional coconut laddus - 200g, made with jaggery', 149.00, 179.00, 250, 'COC-LAD-001', 3, 'Konkan Heritage', 200, 'pack', 0, 0, 0, 0, 'Ratnagiri', 15, 'Fresh Coconut, Jaggery, Cardamom', '{"calories": 120, "serving_size": "30g", "sugar": "12g", "fiber": "2g"}', 'Store in cool place. Refrigerate for longer shelf life.', 4.40, 22, 450, 3000),
('Coconut Barfi (250g)', 'coconut-barfi-250g', 'Soft and delicious coconut barfi made with fresh Konkan coconut and milk. A popular Konkan sweet, perfect for festivals and celebrations.', 'Soft coconut barfi - 250g, traditional Konkan sweet', 179.00, 219.00, 200, 'COC-BRF-001', 3, 'Konkan Heritage', 250, 'pack', 0, 0, 0, 0, 'Goa', 12, 'Fresh Coconut, Milk, Sugar, Cardamom, Ghee', '{"calories": 140, "serving_size": "30g", "sugar": "15g"}', 'Store in cool place or refrigerate.', 4.30, 15, 300, 2200);

-- === CATEGORY 4: KONKAN RICE (Products 66-85) ===
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Indrayani Rice - Premium (5kg)', 'indrayani-rice-premium-5kg', 'Premium Indrayani rice from the foothills of the Sahyadri mountains in Konkan. Known for its distinct aroma, delicate texture, and excellent taste. Traditionally used for making fragrant rice dishes and bhog.', 'Premium Indrayani rice - 5kg, aromatic Konkan rice', 749.00, 949.00, 300, 'RIC-IND-001', 4, 'Konkan Heritage', 5000, 'bag', 1, 1, 0, 1, 'Ratnagiri', 365, 'Premium Indrayani Rice', '{"calories": 130, "serving_size": "100g cooked", "carbohydrates": "28g", "protein": "2.5g", "fiber": "0.4g"}', 'Store in airtight container in cool dry place.', 4.70, 110, 2500, 20000),
('Ambemohar Rice (5kg)', 'ambemohar-rice-5kg', 'Fragrant Ambemohar rice, known as the "mango blossom rice" for its distinct aroma reminiscent of mango blossoms. Grown in the Konkan region, this rice is prized for its unique fragrance, light texture, and delicate flavor.', 'Fragrant Ambemohar rice - 5kg, mango blossom aroma', 899.00, 1099.00, 250, 'RIC-AMB-001', 4, 'Konkan Heritage', 5000, 'bag', 1, 1, 0, 1, 'Sindhudurg', 365, 'Premium Ambemohar Rice', '{"calories": 130, "serving_size": "100g cooked", "carbohydrates": "28g", "protein": "2.5g", "fiber": "0.3g"}', 'Store in airtight container in cool dry place away from strong odors.', 4.60, 85, 2000, 18000),
('Red Rice - Organic (5kg)', 'red-rice-organic-5kg', 'Organic red rice from the Konkan region, unpolished and packed with nutrients. Rich in fiber, iron, and antioxidants. The natural red bran layer gives it a nutty flavor and chewy texture. A healthy alternative to white rice.', 'Organic Red Rice - 5kg, unpolished, nutrient-rich', 649.00, 799.00, 200, 'RIC-RED-001', 4, 'Konkan Bazaar Select', 5000, 'bag', 1, 0, 0, 1, 'Goa', 365, 'Organic Unpolished Red Rice', '{"calories": 120, "serving_size": "100g cooked", "fiber": "3g", "iron": "1.5mg", "magnesium": "45mg"}', 'Store in airtight container in cool dry place.', 4.50, 55, 1500, 14000),
('Govind Bhog Rice (5kg)', 'govind-bhog-rice-5kg', 'Premium Govind Bhog rice from the Konkan region. Known for its sweet aroma and small, short grains. Traditionally used in Bengali cuisine and for making khichdi and payesh.', 'Aromatic Govind Bhog rice - 5kg, small sweet grains', 849.00, 1049.00, 150, 'RIC-GOV-001', 4, 'Konkan Heritage', 5000, 'bag', 0, 0, 0, 0, 'Ratnagiri', 365, 'Premium Govind Bhog Rice', '{"calories": 130, "serving_size": "100g cooked", "carbohydrates": "28g"}', 'Store in airtight container.', 4.30, 20, 400, 5000),
('Basmati Rice - Konkan Gold (5kg)', 'basmati-rice-konkan-gold-5kg', 'Long grain Basmati rice grown in the Konkan region. Fragrant, fluffy, and perfect for biryani and pulao. Each grain remains separate after cooking.', 'Premium Konkan Basmati rice - 5kg, long grain', 699.00, 899.00, 500, 'RIC-BAS-001', 4, 'Konkan Bazaar Select', 5000, 'bag', 0, 1, 0, 0, 'Sindhudurg', 365, 'Premium Basmati Rice', '{"calories": 130, "serving_size": "100g cooked", "carbohydrates": "28g", "protein": "2.6g"}', 'Store in airtight container in cool dry place.', 4.20, 35, 1200, 8000),
('Brown Rice - Organic (5kg)', 'brown-rice-organic-5kg', 'Organic brown rice from the Konkan region. Minimally processed to retain the bran layer and germ. High in fiber, vitamins, and minerals. A healthy whole grain choice.', 'Organic brown rice - 5kg, high fiber whole grain', 549.00, 699.00, 250, 'RIC-BRN-001', 4, 'Konkan Bazaar Select', 5000, 'bag', 0, 0, 0, 1, 'Goa', 365, 'Organic Brown Rice', '{"calories": 110, "serving_size": "100g cooked", "fiber": "3.5g", "protein": "2.5g", "magnesium": "40mg"}', 'Store in airtight container in cool dry place. Refrigerate for longer shelf life.', 4.30, 18, 500, 4500),
('Kolam Rice (5kg)', 'kolam-rice-5kg', 'Premium Kolam rice from the Konkan region. Short-grain, slightly sticky rice known for its sweet taste and soft texture. Perfect for daily consumption and making rice dishes.', 'Soft sweet Kolam rice - 5kg, daily cooking', 599.00, 749.00, 350, 'RIC-KOL-001', 4, 'Konkan Fresh', 5000, 'bag', 0, 0, 0, 0, 'Ratnagiri', 365, 'Premium Kolam Rice', '{"calories": 130, "serving_size": "100g cooked", "carbohydrates": "29g", "protein": "2.4g"}', 'Store in airtight container.', 4.10, 15, 600, 3500),
('Rice Flakes - Poha (1kg)', 'rice-flakes-poha-1kg', 'Traditional Konkan-style poha (rice flakes) made from premium Indrayani rice. Thick, flat rice flakes perfect for making the classic Konkan breakfast dish - Kanda Poha.', 'Traditional Indrayani poha - 1kg, thick flakes', 149.00, 179.00, 600, 'RIC-POH-001', 4, 'Konkan Heritage', 1000, 'pack', 0, 1, 0, 0, 'Sindhudurg', 180, 'Rice Flakes (Poha)', '{"calories": 110, "serving_size": "50g", "carbohydrates": "24g", "fiber": "0.5g"}', 'Store in airtight container in cool dry place.', 4.30, 25, 1000, 5000),
('Puffed Rice - Murmura (500g)', 'puffed-rice-murmura-500g', 'Traditional puffed rice (Murmura) made from premium Konkan rice. Light, crispy, and perfectly puffed. Used for making bhel puri, chivda, and other traditional Konkan snacks.', 'Crispy puffed rice - 500g, for bhel and chivda', 79.00, 99.00, 800, 'RIC-MUR-001', 4, 'Konkan Fresh', 500, 'pack', 0, 0, 0, 0, 'Ratnagiri', 365, 'Puffed Rice', '{"calories": 50, "serving_size": "20g", "carbohydrates": "11g"}', 'Store in airtight container to maintain crispiness.', 4.00, 10, 400, 2500),
('Rice Flour - Organic (2kg)', 'rice-flour-organic-2kg', 'Organic rice flour made from Konkan-grown rice. Finely ground and perfectly textured for making traditional Konkan dishes like pathrode, ambil, and savoury pancakes.', 'Organic rice flour - 2kg, fine ground', 199.00, 249.00, 400, 'RIC-FLR-001', 4, 'Konkan Heritage', 2000, 'pack', 0, 0, 0, 1, 'Goa', 365, 'Organic Rice Flour', '{"calories": 110, "serving_size": "30g", "carbohydrates": "25g", "fiber": "1g"}', 'Store in airtight container in cool dry place.', 4.10, 12, 350, 2000);

-- === CATEGORY 5: KOKUM & BEVERAGES (Products 86-100) ===
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Sol Kadhi Concentrate (750ml)', 'sol-kadhi-concentrate-750ml', 'Authentic Sol Kadhi concentrate made from kokum and fresh coconut milk. A traditional Konkan digestive and cooling beverage. Just add chilled water and stir for an instant refreshing drink.', 'Authentic Sol Kadhi concentrate - 750ml, refreshing Konkan drink', 249.00, 299.00, 400, 'KOK-SOL-001', 5, 'Konkan Heritage', 750, 'bottle', 1, 1, 0, 0, 'Sindhudurg', 365, 'Kokum Extract, Coconut Milk, Garlic, Green Chili, Cumin, Salt', '{"calories": 35, "serving_size": "100ml prepared", "antioxidants": "High"}', 'Store in cool dry place. Refrigerate after opening.', 4.60, 95, 2500, 20000),
('Kokum Juice - Ready to Drink (1L)', 'kokum-juice-ready-to-drink-1l', 'Refreshing kokum juice made from real kokum fruit. A traditional Konkan thirst-quencher with digestive benefits. No artificial colors or flavors.', 'Refreshing kokum juice - 1L, no artificial colors', 179.00, 219.00, 500, 'KOK-JUS-001', 5, 'Konkan Delight', 1000, 'carton', 1, 1, 0, 0, 'Ratnagiri', 180, 'Kokum Juice, Water, Sugar, Salt, Cumin', '{"calories": 60, "serving_size": "200ml", "vitamin_c": "10mg", "antioxidants": "High"}', 'Refrigerate after opening. Consume within 5 days.', 4.50, 60, 2000, 15000),
('Dried Kokum Rind (250g)', 'dried-kokum-rind-250g', 'Premium dried kokum rind from the forests of Konkan. Dark purple, rich in antioxidants and hydroxycitric acid (HCA). Used as a natural souring agent in curries and for making Sol Kadhi.', 'Premium dried kokum rind - 250g, natural souring agent', 199.00, 249.00, 600, 'KOK-DRY-001', 5, 'Konkan Heritage', 250, 'pack', 0, 1, 0, 1, 'Sindhudurg', 540, 'Dried Kokum Rind (Garcinia indica)', '{"calories": 40, "serving_size": "10g", "vitamin_c": "15mg", "antioxidants": "Very High"}', 'Store in airtight container in cool dry place.', 4.50, 45, 1800, 10000),
('Kokum Syrup - Concentrate (500ml)', 'kokum-syrup-concentrate-500ml', 'Rich kokum syrup concentrate made from authentic Konkan kokum. Mix with chilled water or soda for an instant refreshing drink. Perfect summer beverage.', 'Kokum syrup concentrate - 500ml, makes 5L drink', 199.00, 239.00, 350, 'KOK-SYR-001', 5, 'Konkan Delight', 500, 'bottle', 0, 0, 0, 0, 'Ratnagiri', 365, 'Kokum Extract, Sugar, Salt, Cumin, Preservatives (as permitted)', '{"calories": 50, "serving_size": "30ml", "sugar": "12g"}', 'Store in cool dry place. Refrigerate after opening.', 4.20, 20, 600, 3500),
('Tamarind Concentrate (500ml)', 'tamarind-concentrate-500ml', 'Pure tamarind concentrate from premium Konkan tamarind. Rich, tangy, and ready to use. Perfect for curries, chutneys, and traditional Konkan recipes.', 'Pure tamarind concentrate - 500ml, ready to use', 149.00, 179.00, 400, 'KOK-TAM-001', 5, 'Konkan Heritage', 500, 'bottle', 0, 0, 0, 0, 'Goa', 540, 'Tamarind Extract, Water, Preservative (as permitted)', '{"calories": 10, "serving_size": "15ml"}', 'Store in cool dry place.', 4.10, 15, 400, 2500),
('Fresh Lime Juice (1L)', 'fresh-lime-juice-1l', 'Freshly squeezed lime juice from limes grown in the Konkan region. No added water or sugar. Perfect for making limeade, cocktails, and cooking.', 'Fresh squeezed lime juice - 1L, no added water', 199.00, 249.00, 250, 'KOK-LIM-001', 5, 'Konkan Fresh', 1000, 'carton', 0, 0, 0, 0, 'Ratnagiri', 15, 'Fresh Lime Juice', '{"calories": 25, "serving_size": "30ml", "vitamin_c": "15mg"}', 'Refrigerate. Consume within 10 days of opening.', 4.00, 8, 300, 2000),
('Sugarcane Juice - Packaged (1L)', 'sugarcane-juice-packaged-1l', 'Fresh sugarcane juice from Konkan-grown sugarcane. Naturally sweet and refreshing. No added sugar or preservatives. Rich in iron and antioxidants.', 'Fresh sugarcane juice - 1L, natural sweetness', 99.00, 129.00, 300, 'KOK-SUG-001', 5, 'Konkan Fresh', 1000, 'carton', 0, 0, 0, 0, 'Sindhudurg', 45, 'Pure Sugarcane Juice', '{"calories": 110, "serving_size": "200ml", "sugar": "24g", "iron": "1.5mg"}', 'Refrigerate. Consume within 3 days of opening.', 4.00, 10, 400, 2200),
('Buttermilk Masala - Chaas Mix (200g)', 'buttermilk-masala-chaas-mix-200g', 'Traditional Konkan-style buttermilk masala mix. A blend of roasted cumin, black salt, mint, and other spices. Just add to fresh buttermilk for an instant refreshing chaas.', 'Konkan-style chaas masala - 200g, instant mix', 79.00, 99.00, 500, 'KOK-CHA-001', 5, 'Konkan Heritage', 200, 'pack', 0, 0, 0, 0, 'Goa', 540, 'Cumin, Black Salt, Mint, Ginger, Green Chili, Coriander, Salt', '{"calories": 5, "serving_size": "5g"}', 'Store in airtight container in cool dry place.', 4.10, 12, 500, 2200),
('Aamras - Mango Pulp (500g)', 'aamras-mango-pulp-500g', 'Pure Alphonso mango pulp (Aamras) from Devgad mangoes. Rich, thick, and naturally sweet. No added sugar or preservatives. Perfect with puris or as dessert topping.', 'Pure Alphonso aamras - 500g, no added sugar', 349.00, 449.00, 250, 'KOK-AAM-001', 5, 'Konkan Bazaar Select', 500, 'jar', 0, 0, 1, 0, 'Devgad', 365, '100% Alphonso Mango Pulp', '{"calories": 120, "serving_size": "100g", "sugar": "28g"}', 'Store in cool place. Refrigerate after opening.', 4.50, 30, 600, 5000),
('Coconut Water - Tender (1L Tetra)', 'coconut-water-tender-1l-tetra', 'Pure tender coconut water from young Konkan coconuts. Packed in tetra pack to preserve natural electrolytes and freshness. No added sugar.', 'Pure tender coconut water - 1L, natural electrolytes', 120.00, 149.00, 600, 'KOK-CWT-001', 5, 'Konkan Bazaar Select', 1000, 'carton', 0, 0, 0, 0, 'Goa', 180, 'Pure Tender Coconut Water', '{"calories": 45, "serving_size": "240ml", "potassium": "500mg", "sodium": "200mg"}', 'Store at room temperature. Refrigerate for best taste.', 4.10, 18, 700, 3500);

-- === CONTINUED PRODUCTS (101-200) ===
-- I need to add more products to reach 200. Let me add remaining categories.

-- CATEGORY 6: PICKLES & CHUTNEYS (Products 101-115)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Mango Pickle - Traditional (500g)', 'mango-pickle-traditional-500g', 'Traditional Konkan-style mango pickle made from raw green mangoes and a special blend of spices. Aged to perfection for authentic taste. No artificial colors or preservatives.', 'Traditional Konkan mango pickle - 500g, aged recipe', 199.00, 249.00, 500, 'PIC-MAN-001', 6, 'Konkan Heritage', 500, 'jar', 1, 1, 0, 0, 'Ratnagiri', 540, 'Raw Mango, Mustard Oil, Red Chili, Turmeric, Fenugreek, Salt, Vinegar', '{"calories": 25, "serving_size": "15g"}', 'Store in cool dry place. Use dry spoon always.', 4.50, 80, 2000, 12000),
('Lime Pickle - Spicy (500g)', 'lime-pickle-spicy-500g', 'Spicy Konkan-style lime pickle made with fresh limes and traditional spices. Cured to perfection with a perfect balance of tangy, spicy, and salty flavors.', 'Spicy lime pickle - 500g, traditional Konkan style', 179.00, 219.00, 400, 'PIC-LIM-001', 6, 'Konkan Heritage', 500, 'jar', 0, 1, 0, 0, 'Sindhudurg', 540, 'Lime, Red Chili, Mustard Seeds, Fenugreek, Turmeric, Salt, Oil', '{"calories": 20, "serving_size": "15g"}', 'Store in cool dry place.', 4.40, 35, 1000, 6000),
('Mixed Vegetable Pickle (500g)', 'mixed-vegetable-pickle-500g', 'Konkan-style mixed vegetable pickle with carrots, cauliflower, turnip, and green mangoes. A colorful and flavorful pickle made with traditional spice blend.', 'Mixed vegetable pickle - 500g, Konkan style', 199.00, 249.00, 350, 'PIC-MIX-001', 6, 'Konkan Heritage', 500, 'jar', 0, 0, 0, 0, 'Goa', 540, 'Carrots, Cauliflower, Turnip, Green Mango, Mustard Oil, Spices, Salt', '{"calories": 22, "serving_size": "15g"}', 'Store in cool dry place.', 4.20, 18, 500, 3200),
('Garlic Pickle (500g)', 'garlic-pickle-500g', 'Traditional Konkan garlic pickle made with whole garlic cloves and authentic spices. A pungent, flavorful pickle that is a staple in Konkan households.', 'Garlic pickle - 500g, whole cloves, Konkan style', 249.00, 299.00, 300, 'PIC-GAR-001', 6, 'Konkan Heritage', 500, 'jar', 0, 0, 0, 0, 'Ratnagiri', 540, 'Garlic Cloves, Mustard Oil, Red Chili, Vinegar, Salt, Spices', '{"calories": 30, "serving_size": "15g"}', 'Store in cool dry place away from sunlight.', 4.30, 20, 400, 2800),
('Tendli (Ivy Gourd) Pickle (500g)', 'tendli-ivy-gourd-pickle-500g', 'Traditional Konkan-style Tendli (ivy gourd) pickle. Crispy and tangy with authentic Konkan spices. A unique coastal specialty.', 'Konkan-style Tendli pickle - 500g, crispy and tangy', 219.00, 269.00, 250, 'PIC-TEN-001', 6, 'Konkan Heritage', 500, 'jar', 0, 0, 0, 0, 'Sindhudurg', 540, 'Ivy Gourd, Mustard Oil, Red Chili, Turmeric, Mustard Seeds, Salt', '{"calories": 20, "serving_size": "15g"}', 'Store in cool dry place.', 4.10, 12, 300, 2500),
('Coconut Chutney Powder (200g)', 'coconut-chutney-powder-200g', 'Instant coconut chutney powder made from roasted coconut and traditional Konkan spices. Just mix with water or yogurt for instant chutney. Perfect accompaniment for dosa, idli, and rice.', 'Instant coconut chutney powder - 200g, mix and serve', 99.00, 129.00, 600, 'PIC-COC-001', 6, 'Konkan Heritage', 200, 'pack', 0, 1, 0, 0, 'Goa', 365, 'Roasted Coconut, Red Chili, Cumin, Coriander, Tamarind, Salt', '{"calories": 15, "serving_size": "10g"}', 'Store in airtight container in cool dry place.', 4.30, 25, 800, 4500),
('Mint Chutney - Instant Mix (200g)', 'mint-chutney-instant-mix-200g', 'Instant mint chutney mix with authentic Konkan flavors. Blend of dried mint, green chili, and traditional spices. Just add water and fresh mint for delicious chutney.', 'Instant mint chutney mix - 200g, Konkan style', 89.00, 109.00, 500, 'PIC-MIN-001', 6, 'Konkan Heritage', 200, 'pack', 0, 0, 0, 0, 'Ratnagiri', 365, 'Dried Mint, Green Chili, Cumin, Coriander, Salt, Citric Acid', '{"calories": 5, "serving_size": "5g"}', 'Store in airtight container.', 4.00, 10, 350, 2000),
('Dry Chutney - Shenga (Peanut) 250g', 'dry-chutney-shenga-peanut-250g', 'Konkan-style dry peanut chutney (Shenga Chutney). Roasted peanuts with red chili, garlic, and coconut. Perfect side dish for bhakri, rice, or roti.', 'Konkan-style peanut dry chutney - 250g', 129.00, 159.00, 400, 'PIC-PNT-001', 6, 'Konkan Heritage', 250, 'pack', 0, 0, 0, 0, 'Sindhudurg', 120, 'Roasted Peanuts, Red Chili, Garlic, Coconut, Salt', '{"calories": 40, "serving_size": "15g", "protein": "2g"}', 'Store in airtight container in cool dry place.', 4.20, 12, 400, 2500),
('Imli (Tamarind) Chutney (500ml)', 'imli-tamarind-chutney-500ml', 'Sweet and tangy tamarind chutney made from premium Konkan tamarind. Blended with jaggery and traditional spices. Perfect for chaats, samosas, and snacks.', 'Sweet tamarind chutney - 500ml, chaat essential', 149.00, 179.00, 350, 'PIC-IML-001', 6, 'Konkan Delight', 500, 'bottle', 0, 0, 0, 0, 'Goa', 365, 'Tamarind, Jaggery, Cumin, Ginger, Black Salt, Red Chili', '{"calories": 35, "serving_size": "30ml", "sugar": "8g"}', 'Refrigerate after opening.', 4.20, 15, 500, 3000),
('Green Chili Pickle - Konkan Style (300g)', 'green-chili-pickle-konkan-style-300g', 'Fiery green chili pickle made in traditional Konkan style. Fresh green chilies pickled with mustard oil and spices. For the brave spice lovers!', 'Spicy green chili pickle - 300g, Konkan style', 149.00, 189.00, 300, 'PIC-GRC-001', 6, 'Konkan Heritage', 300, 'jar', 0, 0, 0, 0, 'Ratnagiri', 540, 'Green Chili, Mustard Oil, Mustard Seeds, Turmeric, Salt, Vinegar', '{"calories": 15, "serving_size": "10g"}', 'Store in cool dry place.', 4.00, 10, 250, 2000),
('Kairi - Raw Mango Sliced Pickle (500g)', 'kairi-raw-mango-sliced-pickle-500g', 'Sliced raw mango pickle made in traditional Konkan style. Crisp mango slices marinated in aromatic spices and mustard oil. A seasonal favorite.', 'Sliced raw mango pickle - 500g, Konkan style', 179.00, 219.00, 400, 'PIC-KAI-001', 6, 'Konkan Heritage', 500, 'jar', 0, 0, 0, 0, 'Sindhudurg', 540, 'Raw Mango Slices, Mustard Oil, Red Chili, Turmeric, Fenugreek, Salt', '{"calories": 22, "serving_size": "15g"}', 'Store in cool dry place.', 4.30, 18, 450, 2800);

-- CATEGORY 7: CASHEW & DRY FRUITS (Products 116-130)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Roasted Cashew Nuts - Salted (500g)', 'roasted-cashew-nuts-salted-500g', 'Premium roasted cashew nuts from the Konkan region of Goa. Medium-sized, crunchy, and perfectly salted. Sourced from local cashew farms and roasted to golden perfection.', 'Premium roasted salted cashews - 500g, Goan cashews', 549.00, 699.00, 500, 'CAS-ROS-001', 7, 'Konkan Bazaar Select', 500, 'pack', 1, 1, 0, 0, 'Goa', 180, 'Cashew Nuts, Salt, Vegetable Oil', '{"calories": 160, "serving_size": "30g", "protein": "5g", "fat": "13g", "fiber": "1g"}', 'Store in airtight container in cool dry place.', 4.60, 120, 3500, 28000),
('Raw Cashew Nuts - Premium (500g)', 'raw-cashew-nuts-premium-500g', 'Premium raw cashew nuts (Kaju) directly from Konkan cashew farms. W180 grade, large and white. Perfect for making cashew milk, vegan cheese, or homemade roasted cashews.', 'Premium raw cashews - 500g, W180 grade', 499.00, 629.00, 400, 'CAS-RAW-001', 7, 'Konkan Bazaar Select', 500, 'pack', 1, 1, 0, 1, 'Goa', 365, '100% Raw Cashew Nuts', '{"calories": 155, "serving_size": "30g", "protein": "5g", "fat": "12g", "fiber": "1g"}', 'Store in airtight container in cool dry place. Refrigerate for longer shelf life.', 4.50, 75, 2800, 22000),
('Masala Cashew Nuts (500g)', 'masala-cashew-nuts-500g', 'Spiced masala cashew nuts from Konkan. Roasted with a traditional blend of Indian spices - chaat masala, black pepper, and red chili. A perfect party snack.', 'Spiced masala cashews - 500g, Konkan style', 599.00, 749.00, 300, 'CAS-MAS-001', 7, 'Konkan Bazaar Select', 500, 'pack', 0, 1, 0, 0, 'Goa', 180, 'Cashew Nuts, Chaat Masala, Black Pepper, Red Chili, Salt, Oil', '{"calories": 165, "serving_size": "30g", "protein": "5g", "fat": "13g"}', 'Store in airtight container in cool dry place.', 4.50, 45, 2000, 15000),
('Honey Roasted Cashews (500g)', 'honey-roasted-cashews-500g', 'Premium Konkan cashews roasted with a light coating of pure honey and a hint of salt. Sweet and savory combination that makes an irresistible snack.', 'Honey roasted cashews - 500g, sweet and savory', 649.00, 799.00, 250, 'CAS-HON-001', 7, 'Konkan Bazaar Select', 500, 'pack', 0, 0, 0, 0, 'Goa', 180, 'Cashew Nuts, Honey, Sugar, Salt, Oil', '{"calories": 170, "serving_size": "30g", "protein": "4g", "fat": "12g", "sugar": "6g"}', 'Store in airtight container in cool dry place.', 4.40, 30, 1500, 10000),
('Cashew Feni - Premium (750ml)', 'cashew-feni-premium-750ml', 'Premium cashew Feni from Goa, distilled from the fermented juice of cashew apples. A traditional Goan spirit with a distinct fruity aroma and smooth finish. Double distilled for premium quality.', 'Premium Goan Cashew Feni - 750ml, double distilled', 899.00, 1099.00, 100, 'CAS-FEN-001', 7, 'Goan Heritage', 750, 'bottle', 0, 0, 0, 0, 'Goa', 3650, 'Distilled Cashew Apple Ferment', '{"alcohol": "42.8% ABV", "calories": 70, "serving_size": "30ml"}', 'Store in cool dark place away from direct sunlight.', 4.30, 25, 500, 8000),
('Cashew Pieces - Cooking Grade (500g)', 'cashew-pieces-cooking-grade-500g', 'Premium broken cashew pieces from Konkan. Ideal for cooking, making cashew cream, garnishing desserts, and adding to curries. Same premium quality at a more affordable price.', 'Cashew pieces for cooking - 500g, great value', 399.00, 499.00, 600, 'CAS-PCS-001', 7, 'Konkan Bazaar Select', 500, 'pack', 0, 1, 0, 0, 'Goa', 365, 'Cashew Pieces', '{"calories": 155, "serving_size": "30g", "protein": "5g", "fat": "12g"}', 'Store in airtight container in cool dry place.', 4.30, 40, 2000, 8000),
('Cashew Butter - Unsweetened (250g)', 'cashew-butter-unsweetened-250g', 'Pure cashew butter made from roasted Konkan cashews. No added sugar, oil, or preservatives. Creamy, nutty, and rich. Perfect spread on toast or addition to smoothies.', 'Pure cashew butter - 250g, unsweetened, creamy', 449.00, 549.00, 200, 'CAS-BUT-001', 7, 'Konkan Bazaar Select', 250, 'jar', 0, 0, 0, 1, 'Goa', 180, '100% Roasted Cashew Nuts', '{"calories": 180, "serving_size": "30g", "protein": "6g", "fat": "15g", "fiber": "1g"}', 'Store in cool dry place. Natural oil separation is normal - stir before use.', 4.30, 15, 400, 3500),
('Kaju Katli - Premium (500g)', 'kaju-katli-premium-500g', 'Premium Kaju Katli made from fresh Konkan cashew paste and pure ghee. Soft, melt-in-the-mouth texture with authentic taste. Adorned with silver vark. Perfect festival gift.', 'Premium Kaju Katli - 500g, authentic cashew sweet', 799.00, 999.00, 150, 'CAS-KAT-001', 7, 'Konkan Heritage', 500, 'box', 0, 1, 0, 0, 'Goa', 45, 'Cashew Paste, Sugar, Ghee, Cardamom, Silver Vark', '{"calories": 120, "serving_size": "25g", "sugar": "10g", "fat": "7g"}', 'Store in cool dry place in airtight container. Refrigerate for longer shelf life.', 4.60, 35, 800, 6000),
('Cashew Milk - Unsweetened (1L)', 'cashew-milk-unsweetened-1l', 'Creamy cashew milk made from premium Konkan cashews. Dairy-free, lactose-free, and vegan. No added sugar. Perfect for coffee, cereal, and smoothies.', 'Unsweetened cashew milk - 1L, dairy-free', 249.00, 299.00, 200, 'CAS-MLK-001', 7, 'Konkan Bazaar Select', 1000, 'carton', 0, 0, 0, 1, 'Goa', 120, 'Filtered Water, Cashews, Sea Salt', '{"calories": 35, "serving_size": "240ml", "protein": "1g", "fat": "3g"}', 'Refrigerate. Shake well before use. Consume within 7 days of opening.', 4.10, 10, 250, 2200),
('Almonds - Mamra (500g)', 'almonds-mamra-500g', 'Premium Mamra almonds from the Konkan region. Small, sweet, and nutrient-dense. Known for their superior taste and higher oil content compared to regular almonds.', 'Premium Mamra almonds - 500g, sweet and nutrient-rich', 649.00, 799.00, 200, 'CAS-ALM-001', 7, 'Konkan Bazaar Select', 500, 'pack', 0, 0, 0, 1, 'Sindhudurg', 365, 'Mamra Almonds', '{"calories": 165, "serving_size": "30g", "protein": "6g", "fat": "14g", "vitamin_e": "7.5mg"}', 'Store in airtight container in cool dry place.', 4.40, 15, 500, 3500);

-- CATEGORY 8: NATURAL SPICES (Products 131-150)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Organic Black Pepper - Whole (200g)', 'organic-black-pepper-whole-200g', 'Premium organic black pepper from the spice gardens of Konkan. Bold, aromatic peppercorns with high piperine content. Freshly harvested and sun-dried.', 'Organic whole black pepper - 200g, Konkan spice gardens', 299.00, 379.00, 400, 'SPI-PEP-001', 8, 'Konkan Heritage', 200, 'pack', 1, 1, 0, 1, 'Sindhudurg', 730, 'Organic Black Peppercorns', '{"calories": 5, "serving_size": "2g", "fiber": "0.5g", "piperine": "High"}', 'Store in airtight container away from sunlight. Grind fresh for best flavor.', 4.60, 80, 2500, 18000),
('Fresh Turmeric Root (500g)', 'fresh-turmeric-root-500g', 'Fresh organic turmeric root from Konkan farms. Bright orange flesh with high curcumin content. Used fresh in cooking, teas, and traditional remedies.', 'Fresh organic turmeric root - 500g, high curcumin', 149.00, 189.00, 300, 'SPI-TUR-001', 8, 'Konkan Heritage', 500, 'pack', 0, 1, 0, 1, 'Goa', 21, 'Fresh Turmeric Root', '{"calories": 10, "serving_size": "10g", "curcumin": "High", "fiber": "0.5g"}', 'Store in refrigerator in paper bag. Can be frozen for longer storage.', 4.40, 30, 1200, 8000),
('Organic Red Chili Powder (200g)', 'organic-red-chili-powder-200g', 'Premium organic red chili powder made from Konkan-grown Byadgi chilies. Vibrant red color with moderate heat. Authentic spice essential for Konkan cuisine.', 'Organic Byadgi chili powder - 200g, vibrant red', 149.00, 189.00, 500, 'SPI-CHP-001', 8, 'Konkan Heritage', 200, 'pack', 0, 1, 0, 1, 'Ratnagiri', 540, 'Organic Byadgi Red Chilies', '{"calories": 10, "serving_size": "5g", "vitamin_a": "500mcg", "capsaicin": "Moderate"}', 'Store in airtight container away from sunlight.', 4.30, 35, 1500, 7000),
('Coriander Seeds - Whole (200g)', 'coriander-seeds-whole-200g', 'Premium whole coriander seeds from the Konkan region. Aromatic and flavorful, freshly harvested from organic farms. Essential for spice blends and cooking.', 'Aromatic coriander seeds - 200g, Konkan grown', 89.00, 109.00, 600, 'SPI-COR-001', 8, 'Konkan Heritage', 200, 'pack', 0, 0, 0, 1, 'Sindhudurg', 730, 'Organic Coriander Seeds', '{"calories": 5, "serving_size": "5g", "fiber": "1g"}', 'Store in airtight container in cool dry place.', 4.20, 15, 600, 3500),
('Cumin Seeds - Jeera (200g)', 'cumin-seeds-jeera-200g', 'Premium cumin seeds from Konkan farms. Strong, aromatic, and freshly harvested. An essential spice for all Indian cooking.', 'Premium cumin seeds - 200g, aromatic Konkan jeera', 99.00, 129.00, 600, 'SPI-CUM-001', 8, 'Konkan Heritage', 200, 'pack', 0, 0, 0, 1, 'Ratnagiri', 730, 'Organic Cumin Seeds', '{"calories": 8, "serving_size": "5g", "iron": "1.5mg"}', 'Store in airtight container in cool dry place.', 4.10, 12, 500, 3000),
('Konkan Garam Masala - Blend (200g)', 'konkan-garam-masala-blend-200g', 'Special Konkan-style garam masala blend made with traditional coastal spices. Cardamom, cinnamon, cloves, nutmeg, and pepper from the region. Perfect for Konkan curries.', 'Konkan-style garam masala - 200g, coastal blend', 199.00, 249.00, 400, 'SPI-GRM-001', 8, 'Konkan Heritage', 200, 'pack', 0, 1, 0, 0, 'Goa', 540, 'Cardamom, Cinnamon, Cloves, Nutmeg, Black Pepper, Mace, Bay Leaf', '{"calories": 8, "serving_size": "5g"}', 'Store in airtight container away from sunlight.', 4.50, 40, 1800, 6500),
('Goda Masala - Konkan Special (200g)', 'goda-masala-konkan-special-200g', 'Authentic Goda masala, a traditional Konkan spice blend. Sweet, aromatic, and mild. Essential for Malvani and Konkan cuisine. Made with 15+ spices.', 'Authentic Goda masala - 200g, Konkan special blend', 179.00, 219.00, 350, 'SPI-GOD-001', 8, 'Konkan Heritage', 200, 'pack', 1, 1, 0, 0, 'Sindhudurg', 540, 'Coriander, Cumin, Pepper, Cloves, Cardamom, Cinnamon, Bay Leaf, Sesame, Coconut, Mace', '{"calories": 10, "serving_size": "5g"}', 'Store in airtight container in cool dry place.', 4.60, 50, 2000, 8000),
('Whole Cardamom - Green (100g)', 'whole-cardamom-green-100g', 'Premium green cardamom (Elaichi) from the Konkan region. Highly aromatic with intense essential oils. Perfect for sweets, chai, and biryani.', 'Premium green cardamom - 100g, highly aromatic', 449.00, 549.00, 200, 'SPI-CRD-001', 8, 'Konkan Heritage', 100, 'pack', 0, 0, 0, 1, 'Goa', 730, 'Green Cardamom Pods', '{"calories": 5, "serving_size": "2g", "essential_oils": "High"}', 'Store in airtight container away from sunlight and moisture.', 4.40, 18, 600, 4000),
('Cloves - Laung (100g)', 'cloves-laung-100g', 'Premium cloves from the Konkan spice gardens. Dark brown, oil-rich with intense aroma. Handpicked and sun-dried for premium quality.', 'Premium cloves - 100g, Konkan spice garden', 199.00, 249.00, 300, 'SPI-CLO-001', 8, 'Konkan Heritage', 100, 'pack', 0, 0, 0, 1, 'Sindhudurg', 730, 'Whole Cloves', '{"calories": 5, "serving_size": "2g", "eugenol": "High"}', 'Store in airtight container away from light.', 4.20, 12, 400, 2800),
('Cinnamon Sticks - Dalchini (100g)', 'cinnamon-sticks-dalchini-100g', 'Premium cinnamon sticks (Dalchini) from Konkan region. Thin, layered bark with sweet, warm flavor. Perfect for biryani, chai, and desserts.', 'Premium cinnamon sticks - 100g, Konkan grown', 149.00, 189.00, 350, 'SPI-CIN-001', 8, 'Konkan Heritage', 100, 'pack', 0, 0, 0, 1, 'Ratnagiri', 730, 'Cinnamon Sticks', '{"calories": 5, "serving_size": "2g", "fiber": "1g"}', 'Store in airtight container in cool dry place.', 4.10, 10, 350, 2200),
('Dry Red Byadgi Chili (200g)', 'dry-red-byadgi-chili-200g', 'Premium Byadgi red chilies from Konkan farms. Deep red color, mild heat, and rich color. Essential for authentic Konkan cuisine and giving vibrant red color to dishes.', 'Byadgi red chilies - 200g, vibrant color, mild heat', 129.00, 159.00, 400, 'SPI-BYD-001', 8, 'Konkan Heritage', 200, 'pack', 0, 0, 0, 1, 'Ratnagiri', 540, 'Dried Byadgi Red Chilies', '{"calories": 10, "serving_size": "5g", "vitamin_a": "High"}', 'Store in airtight container away from moisture.', 4.20, 15, 500, 3000);

-- CATEGORY 9: ORGANIC JAGGERY & SWEETENERS (Products 151-160)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Organic Jaggery - Pure (1kg)', 'organic-jaggery-pure-1kg', 'Pure organic jaggery (Gud) made from sugarcane grown in the Konkan region. Golden brown, rich in iron and minerals. Traditionally processed without chemicals.', 'Pure organic jaggery - 1kg, iron-rich Konkan gud', 249.00, 299.00, 500, 'JAG-PUR-001', 9, 'Konkan Heritage', 1000, 'block', 1, 1, 0, 1, 'Ratnagiri', 540, 'Organic Sugarcane Jaggery', '{"calories": 40, "serving_size": "10g", "iron": "1.5mg", "calcium": "8mg", "magnesium": "5mg"}', 'Store in airtight container in cool dry place. May become soft in humid weather.', 4.50, 60, 2000, 14000),
('Palm Jaggery - Karupatti (1kg)', 'palm-jaggery-karupatti-1kg', 'Premium palm jaggery (Karupatti/Panai Vellam) from the Konkan region. Made from palm tree sap, rich in minerals with a distinct caramel-like flavor. Low glycemic index.', 'Palm jaggery - 1kg, low glycemic, mineral-rich', 399.00, 499.00, 250, 'JAG-PAL-001', 9, 'Konkan Heritage', 1000, 'block', 1, 0, 0, 1, 'Goa', 540, 'Pure Palm Jaggery', '{"calories": 35, "serving_size": "10g", "iron": "2mg", "calcium": "15mg", "glycemic_index": "Low"}', 'Store in airtight container in cool dry place.', 4.40, 25, 800, 6000),
('Coconut Jaggery - Organic (500g)', 'coconut-jaggery-organic-500g', 'Organic coconut jaggery made from the sap of coconut palm flowers. Rich, caramel-like sweetness with a low glycemic index. Mineral-rich and naturally processed.', 'Organic coconut jaggery - 500g, low glycemic', 299.00, 379.00, 300, 'JAG-COC-001', 9, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 1, 'Sindhudurg', 540, 'Organic Coconut Palm Jaggery', '{"calories": 38, "serving_size": "10g", "potassium": "130mg", "magnesium": "10mg"}', 'Store in airtight container in cool dry place.', 4.30, 15, 500, 3500),
('Jaggery Powder - Organic (500g)', 'jaggery-powder-organic-500g', 'Organic jaggery powder from Konkan sugarcane. Finely ground for easy use in cooking and baking. No additives or anti-caking agents.', 'Organic jaggery powder - 500g, fine ground', 179.00, 219.00, 400, 'JAG-PWD-001', 9, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 1, 'Ratnagiri', 540, 'Organic Jaggery Powder', '{"calories": 38, "serving_size": "10g", "iron": "1.2mg"}', 'Store in airtight container in cool dry place.', 4.10, 12, 400, 2500),
('Wild Honey - Raw (500ml)', 'wild-honey-raw-500ml', 'Pure raw wild honey from the forests of Konkan. Harvested from indigenous wild bee colonies in the Sahyadri forests. Rich, complex flavor with medicinal properties. Unfiltered and unpasteurized.', 'Raw wild honey - 500ml, Sahyadri forest honey', 899.00, 1099.00, 150, 'JAG-HON-001', 9, 'Konkan Heritage', 500, 'bottle', 1, 1, 0, 1, 'Sindhudurg', 1825, '100% Raw Wild Honey', '{"calories": 65, "serving_size": "20g", "sugar": "16g", "antioxidants": "High"}', 'Store in cool dry place away from direct sunlight. Natural crystallization may occur.', 4.70, 45, 1200, 10000),
('Multiflora Honey (500ml)', 'multiflora-honey-500ml', 'Pure multiflora honey from Konkan region apiaries. Bees collect nectar from diverse Konkan flora including mango blossoms, coconut flowers, and wildflowers. Smooth and sweet.', 'Multiflora honey - 500ml, Konkan blossoms', 499.00, 629.00, 300, 'JAG-HON-002', 9, 'Konkan Heritage', 500, 'bottle', 0, 0, 0, 1, 'Goa', 1825, '100% Pure Multiflora Honey', '{"calories": 65, "serving_size": "20g", "sugar": "16g"}', 'Store in cool dry place.', 4.30, 18, 600, 4500),
('Date Syrup (500ml)', 'date-syrup-500ml', 'Natural date syrup made from premium Medjool dates. No added sugar, no preservatives. A healthy, iron-rich natural sweetener. Perfect for drizzling over desserts, pancakes, or in smoothies.', 'Natural date syrup - 500ml, iron-rich sweetener', 349.00, 429.00, 200, 'JAG-DAT-001', 9, 'Konkan Bazaar Select', 500, 'bottle', 0, 0, 0, 1, 'Ratnagiri', 365, 'Date Extract', '{"calories": 60, "serving_size": "20g", "sugar": "14g", "iron": "1mg", "potassium": "120mg"}', 'Store in cool dry place. Refrigerate after opening.', 4.20, 10, 250, 2000);

-- CATEGORY 10: TRADITIONAL SNACKS (Products 161-175)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Chakli - Konkan Style (500g)', 'chakli-konkan-style-500g', 'Crispy, spiral-shaped Konkan-style chakli (murukku) made from rice flour, gram flour, and traditional spices. Perfect tea-time snack, deep fried to golden perfection.', 'Crispy Konkan chakli - 500g, traditional spiral snack', 199.00, 249.00, 500, 'SNK-CHK-001', 10, 'Konkan Heritage', 500, 'pack', 1, 1, 0, 0, 'Ratnagiri', 60, 'Rice Flour, Gram Flour, Cumin Seeds, Sesame Seeds, Butter, Salt, Oil', '{"calories": 80, "serving_size": "20g", "fat": "4g", "fiber": "1g"}', 'Store in airtight container in cool dry place.', 4.40, 55, 2000, 12000),
('Kanda Poha - Instant Mix (500g)', 'kanda-poha-instant-mix-500g', 'Instant Kanda Poha mix from Konkan. Just add water and microwave for authentic Konkan breakfast. Made with thick Indrayani poha, roasted peanuts, and traditional spices.', 'Instant Kanda Poha mix - 500g, just add water', 149.00, 179.00, 400, 'SNK-POH-001', 10, 'Konkan Heritage', 500, 'pack', 0, 1, 0, 0, 'Sindhudurg', 180, 'Poha (Rice Flakes), Roasted Peanuts, Onion Flakes, Curry Leaves, Mustard Seeds, Turmeric, Salt, Sugar', '{"calories": 120, "serving_size": "50g prepared", "carbohydrates": "22g", "protein": "3g"}', 'Store in airtight container in cool dry place.', 4.30, 25, 1200, 5000),
('Bhakri - Jowar (10 pcs)', 'bhakri-jowar-10-pcs', 'Traditional Konkan-style Jowar (sorghum) bhakri. Hand-rolled and freshly prepared. A staple bread of Konkan region, perfect with brinjal bharta, curries, or chutney.', 'Traditional Jowar bhakri - 10 pieces, Konkan staple', 179.00, 219.00, 200, 'SNK-BHK-001', 10, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 0, 'Goa', 7, 'Jowar Flour, Water, Salt', '{"calories": 80, "serving_size": "1 bhakri", "fiber": "2g", "protein": "3g"}', 'Store in refrigerator. Reheat on tava before serving.', 4.20, 12, 350, 3000),
('Murukku - Spicy (500g)', 'murukku-spicy-500g', 'Spicy Konkan-style murukku made with rice flour, gram flour, and red chili. Extra crispy with a perfect crunch. An addictive tea-time snack.', 'Spicy murukku - 500g, Konkan style, extra crispy', 219.00, 269.00, 350, 'SNK-MUR-001', 10, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 0, 'Ratnagiri', 60, 'Rice Flour, Gram Flour, Red Chili Powder, Cumin Seeds, Butter, Salt, Oil', '{"calories": 85, "serving_size": "20g", "fat": "4.5g"}', 'Store in airtight container.', 4.30, 18, 600, 3500),
('Chivda - Pohe Mixture (500g)', 'chivda-pohe-mixture-500g', 'Konkan-style chivda made with thick poha (rice flakes), roasted peanuts, cashews, curry leaves, and spices. A traditional Konkan snack mix, perfect for travel and tea-time.', 'Konkan chivda - 500g, poha snack mix with nuts', 179.00, 219.00, 450, 'SNK-CHV-001', 10, 'Konkan Heritage', 500, 'pack', 0, 1, 0, 0, 'Sindhudurg', 90, 'Poha, Peanuts, Cashews, Curry Leaves, Mustard Seeds, Turmeric, Chili, Salt, Oil, Sugar', '{"calories": 90, "serving_size": "20g", "fat": "4g", "protein": "2g"}', 'Store in airtight container in cool dry place.', 4.30, 22, 900, 4500),
('Sabudana Khichdi Mix (500g)', 'sabudana-khichdi-mix-500g', 'Instant Sabudana khichdi mix from Konkan. Premium sabudana (tapioca pearls) pre-mixed with roasted peanuts and spices. Just soak and cook for a delicious fasting dish.', 'Instant Sabudana khichdi mix - 500g, fasting special', 199.00, 249.00, 300, 'SNK-SAB-001', 10, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 0, 'Goa', 180, 'Sabudana (Tapioca Pearls), Roasted Peanuts, Cumin, Green Chili, Salt, Sugar, Ghee', '{"calories": 150, "serving_size": "50g prepared", "carbohydrates": "32g", "protein": "2g"}', 'Store in airtight container in cool dry place.', 4.10, 10, 300, 2500),
('Roasted Bengal Gram - Daliya (500g)', 'roasted-bengal-gram-daliya-500g', 'Roasted Bengal gram (Daliya/Chana Dal) from Konkan. Lightly roasted for a nutty, crunchy snack. High in protein and fiber. A healthy traditional Konkan snack.', 'Roasted Bengal gram - 500g, protein-rich snack', 129.00, 159.00, 500, 'SNK-DAL-001', 10, 'Konkan Heritage', 500, 'pack', 0, 0, 0, 0, 'Ratnagiri', 365, 'Roasted Bengal Gram, Salt', '{"calories": 60, "serving_size": "20g", "protein": "4g", "fiber": "2.5g"}', 'Store in airtight container in cool dry place.', 4.00, 8, 350, 2000),
('Peanut Chikki (250g)', 'peanut-chikki-250g', 'Traditional Konkan-style peanut chikki (gachak). Crunchy peanuts bound in pure jaggery syrup. A classic Konkan winter snack that is both delicious and nutritious.', 'Traditional peanut chikki - 250g, jaggery based', 149.00, 189.00, 350, 'SNK-CHI-001', 10, 'Konkan Heritage', 250, 'pack', 0, 1, 0, 0, 'Sindhudurg', 90, 'Peanuts, Jaggery, Ghee', '{"calories": 110, "serving_size": "25g", "protein": "4g", "sugar": "12g"}', 'Store in airtight container in cool dry place.', 4.40, 20, 800, 4000),
('Til Laddoo - Sesame (250g)', 'til-laddoo-sesame-250g', 'Traditional Konkan-style til (sesame) laddoos made with black sesame seeds and jaggery. A winter special sweet that is rich in calcium and iron. Made during Makar Sankranti.', 'Sesame laddoos - 250g, calcium-rich winter sweet', 179.00, 219.00, 250, 'SNK-TIL-001', 10, 'Konkan Heritage', 250, 'pack', 0, 0, 0, 0, 'Goa', 60, 'Black Sesame Seeds, Jaggery, Peanuts, Cardamom', '{"calories": 130, "serving_size": "25g", "calcium": "100mg", "iron": "2mg"}', 'Store in airtight container in cool dry place.', 4.30, 12, 350, 2800),
('Puran Poli - Ready to Eat (4 pcs)', 'puran-poli-ready-to-eat-4-pcs', 'Traditional Konkan-style Puran Poli. Soft wheat rotis stuffed with sweet chana dal filling (puran). Heat and serve. A festive Maharashtrian delicacy.', 'Ready-to-eat Puran Poli - 4 pieces, festive sweet', 249.00, 299.00, 150, 'SNK-PUR-001', 10, 'Konkan Heritage', 400, 'pack', 0, 0, 0, 0, 'Ratnagiri', 15, 'Wheat Flour, Chana Dal, Jaggery, Cardamom, Nutmeg, Ghee', '{"calories": 200, "serving_size": "1 piece", "sugar": "15g", "protein": "5g"}', 'Store in refrigerator. Reheat on tava before serving.', 4.40, 15, 250, 3500);

-- CATEGORY 11: HANDMADE CRAFTS (Products 176-185)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Handwoven Bamboo Basket - Medium', 'handwoven-bamboo-basket-medium', 'Handcrafted bamboo basket woven by skilled Konkan artisans. Made from sustainably harvested bamboo. Perfect for storage, shopping, or home decor. Each piece is unique.', 'Handwoven Konkan bamboo basket - Medium, artisan made', 599.00, 749.00, 50, 'CRF-BAM-001', 11, 'Konkan Heritage', 500, 'piece', 0, 0, 0, 0, 'Sindhudurg', 9999, 'Natural Bamboo', '{"craft": "Handwoven Bamboo", "material": "Natural Bamboo"}', 'Keep in dry place. Wipe with dry cloth. Avoid moisture.', 4.50, 15, 150, 2500),
('Konkan Clay Diya Set (6 pcs)', 'konkan-clay-diya-set-6-pcs', 'Handcrafted clay diyas (lamps) from Konkan potters. Each diya is shaped, sun-dried, and naturally finished. Perfect for Diwali and festive decorations.', 'Handcrafted clay diyas - 6 pieces, Konkan pottery', 249.00, 299.00, 100, 'CRF-DIY-001', 11, 'Konkan Heritage', 600, 'set', 0, 0, 0, 0, 'Ratnagiri', 9999, 'Natural Clay', '{"craft": "Clay Pottery", "material": "Natural Clay"}', 'Handle with care. Store in dry place.', 4.30, 8, 200, 1800),
('Souvenir - Konkan Coconut Shell Carving', 'souvenir-konkan-coconut-shell-carving', 'Intricately carved coconut shell souvenir from Konkan. Each piece hand-carved by local artisans depicting traditional Konkan scenes. Unique gift item.', 'Hand-carved coconut shell - Konkan souvenir, artisan craft', 399.00, 499.00, 75, 'CRF-COC-001', 11, 'Konkan Heritage', 200, 'piece', 0, 0, 0, 0, 'Goa', 9999, 'Dried Coconut Shell', '{"craft": "Coconut Shell Carving", "material": "Coconut Shell"}', 'Handle with care. Keep in dry place.', 4.40, 10, 100, 1500),
('Konkan Handloom Cotton Towel (2 pcs)', 'konkan-handloom-cotton-towel-2-pcs', 'Handwoven cotton towels from Konkan handloom weavers. Soft, absorbent, and lightweight. Traditional Konkan checkered pattern. Eco-friendly and sustainable.', 'Handloom cotton towels - 2 pieces, Konkan weave', 449.00, 549.00, 80, 'CRF-TOW-001', 11, 'Konkan Heritage', 400, 'set', 0, 0, 0, 1, 'Sindhudurg', 9999, '100% Handloom Cotton', '{"craft": "Handloom Weaving", "material": "Cotton"}', 'Machine washable. Wash before first use.', 4.30, 8, 120, 1200),
('Konkan Spice Box - Wooden (7 Spice)', 'konkan-spice-box-wooden-7-spice', 'Traditional Konkan wooden spice box (Masala Dabba) with 7 stainless steel cups. Handcrafted from locally sourced mango wood. Perfect kitchen companion for Konkan cooking.', 'Handcrafted wooden spice box - 7 spice, mango wood', 799.00, 999.00, 60, 'CRF-SPX-001', 11, 'Konkan Heritage', 800, 'piece', 0, 0, 0, 0, 'Ratnagiri', 9999, 'Mango Wood, Stainless Steel, Natural Lacquer', '{"craft": "Wood Carving", "material": "Mango Wood"}', 'Wipe with dry cloth. Keep away from water. Apply coconut oil occasionally.', 4.60, 20, 250, 3000);

-- CATEGORY 12: MONSOON SPECIALS (Products 186-200)
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Monsoon Bhajji Mix - Special (500g)', 'monsoon-bhajji-mix-special-500g', 'Special Konkan monsoon bhajji (pakora) mix. A blend of gram flour, rice flour, and traditional spices. Just add sliced onions, chilies, or vegetables and fry for crispy monsoon bhajjis.', 'Monsoon bhajji mix - 500g, crispy pakora mix', 149.00, 179.00, 500, 'MON-BHA-001', 12, 'Konkan Heritage', 500, 'pack', 1, 1, 1, 0, 'Ratnagiri', 180, 'Gram Flour, Rice Flour, Red Chili, Cumin, Ajwain, Salt, Baking Soda', '{"calories": 60, "serving_size": "20g prepared", "fat": "3g"}', 'Store in airtight container in cool dry place.', 4.30, 30, 1200, 6000),
('Monsoon Special - Dried Shrimp Bhaji Mix (300g)', 'monsoon-special-dried-shrimp-bhaji-mix-300g', 'Special Konkan monsoon mix with dried shrimp and spices. Just add water and fry for an authentic coastal fritter that pairs perfectly with hot chai on rainy days.', 'Dried shrimp bhaji mix - 300g, coastal monsoon snack', 199.00, 249.00, 300, 'MON-SHR-001', 12, 'Konkan Heritage', 300, 'pack', 0, 0, 1, 0, 'Sindhudurg', 180, 'Dried Shrimp, Gram Flour, Rice Flour, Red Chili, Spices, Salt', '{"calories": 70, "serving_size": "20g"}', 'Store in airtight container in cool dry place.', 4.20, 12, 350, 2800),
('Hot Masala Tea - Konkan Chai Mix (500g)', 'hot-masala-tea-konkan-chai-mix-500g', 'Special Konkan masala chai mix with cardamom, ginger, cinnamon, and black pepper. Just add to milk and tea leaves for authentic Konkan-style cutting chai. Perfect for monsoon evenings.', 'Konkan masala chai mix - 500g, monsoon companion', 249.00, 299.00, 400, 'MON-TEA-001', 12, 'Konkan Heritage', 500, 'pack', 0, 1, 1, 0, 'Goa', 365, 'Tea Powder, Cardamom, Ginger, Cinnamon, Black Pepper, Cloves, Mace', '{"calories": 5, "serving_size": "5g"}', 'Store in airtight container in cool dry place.', 4.50, 35, 1500, 6500),
('Corn Roasted - Bhutta Masala (200g)', 'corn-roasted-bhutta-masala-200g', 'Special Konkan-style roasted corn (bhutta) seasoning mix. A tangy, spicy blend with lemon, chili, and special Konkan spices. Sprinkle on roasted corn for the perfect monsoon street food experience.', 'Bhutta masala seasoning - 200g, monsoon street food', 89.00, 109.00, 500, 'MON-BHU-001', 12, 'Konkan Heritage', 200, 'pack', 0, 0, 1, 0, 'Ratnagiri', 540, 'Red Chili, Lemon Powder, Cumin, Black Salt, Coriander, Mango Powder', '{"calories": 5, "serving_size": "5g"}', 'Store in airtight container.', 4.10, 10, 400, 2000),
('Soup Mix - Konkan Tomato Rasam (200g)', 'soup-mix-konkan-tomato-rasam-200g', 'Instant Konkan-style tomato rasam mix. A warm, spicy-sour soup that is a monsoon favorite. Made with authentic Konkan spices. Just add water, tomatoes, and simmer.', 'Instant tomato rasam mix - 200g, warm monsoon soup', 99.00, 129.00, 400, 'MON-RAS-001', 12, 'Konkan Heritage', 200, 'pack', 0, 0, 1, 0, 'Sindhudurg', 365, 'Coriander, Cumin, Pepper, Red Chili, Turmeric, Asafoetida, Garlic, Tamarind, Salt', '{"calories": 10, "serving_size": "10g"}', 'Store in airtight container in cool dry place.', 4.20, 12, 500, 3000),
('Bhel Puri Mix (500g)', 'bhel-puri-mix-500g', 'Ready-to-eat bhel puri mix from Konkan. Crispy puffed rice, sev, peanuts, and spices in perfect proportion. Just add chutneys and chopped onions for instant bhel puri - the perfect monsoon snack.', 'Ready bhel puri mix - 500g, instant monsoon snack', 149.00, 179.00, 400, 'MON-BHE-001', 12, 'Konkan Heritage', 500, 'pack', 0, 0, 1, 0, 'Goa', 60, 'Puffed Rice, Sev, Peanuts, Roasted Gram, Onion, Tomato Powder, Spices, Salt', '{"calories": 80, "serving_size": "20g", "fat": "3g"}', 'Store in airtight container in cool dry place.', 4.20, 15, 600, 3500);

-- UPDATE PRODUCT COUNTS AS needed
INSERT INTO products (name, slug, description, short_description, price, mrp, stock_quantity, sku, category_id, brand, weight_grams, unit, is_featured, is_bestseller, is_seasonal, is_organic, region_origin, shelf_life_days, ingredients, nutritional_info, storage_instructions, average_rating, review_count, total_sold, views_count) VALUES
('Kokum Sharbat - Concentrate (1L)', 'kokum-sharbat-concentrate-1l', 'Traditional Konkan Kokum Sharbat concentrate. Made from real kokum extract with a hint of cumin and black salt. A digestive and cooling drink perfect for summer and monsoon.', 'Kokum Sharbat concentrate - 1L, digestive drink', 249.00, 299.00, 300, 'BEV-KOK-001', 5, 'Konkan Delight', 1000, 'bottle', 0, 0, 0, 0, 'Ratnagiri', 365, 'Kokum Extract, Sugar, Cumin, Black Salt, Water', '{"calories": 45, "serving_size": "30ml", "sugar": "10g"}', 'Store in cool dry place. Refrigerate after opening.', 4.30, 20, 500, 3500),
('Salted Cashew - Premium (1kg)', 'salted-cashew-premium-1kg', 'Premium salted cashew nuts in bulk pack. W180 grade cashews from Goa, roasted and lightly salted. Perfect for parties, gifting, and everyday snacking.', 'Premium salted cashews - 1kg, party pack', 999.00, 1249.00, 200, 'CAS-SAL-BULK-001', 7, 'Konkan Bazaar Select', 1000, 'pack', 0, 0, 0, 0, 'Goa', 180, 'Cashew Nuts, Salt, Vegetable Oil', '{"calories": 160, "serving_size": "30g", "protein": "5g", "fat": "13g"}', 'Store in airtight container in cool dry place.', 4.50, 25, 800, 5000),
('Spicy Cashew - Extra Hot (500g)', 'spicy-cashew-extra-hot-500g', 'Extra hot spicy cashew nuts for daring snack lovers. Konkan cashews coated with fiery red chili and special spice blend. Not for the faint-hearted!', 'Extra hot spicy cashews - 500g, fiery snack', 579.00, 729.00, 200, 'CAS-SPX-001', 7, 'Konkan Bazaar Select', 500, 'pack', 0, 0, 0, 0, 'Goa', 180, 'Cashew Nuts, Red Chili, Chaat Masala, Black Pepper, Salt, Oil', '{"calories": 165, "serving_size": "30g", "protein": "5g", "fat": "13g"}', 'Store in airtight container.', 4.20, 15, 500, 3500);

-- ============================================================
-- PRODUCT IMAGES (sample data)
-- ============================================================
INSERT INTO product_images (product_id, image_url, alt_text, sort_order, is_primary) VALUES
(1, 'https://images.unsplash.com/photo-1551434678-e076238b5f42?w=600', 'Devgad Alphonso Mango Box', 0, 1),
(1, 'https://images.unsplash.com/photo-1551677740-d80f6f958238?w=600', 'Alphonso Mango Cut', 1, 0),
(2, 'https://images.unsplash.com/photo-1547514701-4270d6d3bb80?w=600', 'Ratnagiri Alphonso Mangoes', 0, 1),
(3, 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600', 'Mango Pulp Jar', 0, 1),
(5, 'https://images.unsplash.com/photo-1551434678-e076238b5f42?w=600', 'Payri Mango', 0, 1);

-- More images are truncated for brevity but would be added in production

-- ============================================================
-- COUPONS
-- ============================================================
-- Coupons use relative dates so they remain active regardless of when the seed is run
INSERT INTO coupons (code, type, value, min_order_amount, max_discount, usage_limit, is_active, valid_from, valid_until, description) VALUES
('KONKAN100', 'flat', 100.00, 299.00, 100.00, 1000, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), 'Flat ₹100 off on orders above ₹299'),
('FIRST20', 'percentage', 20.00, 499.00, 200.00, 500, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), '20% off on first order (max ₹200)'),
('FREESHIP', 'free_shipping', 0.00, 499.00, NULL, 9999, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), 'Free shipping on all orders above ₹499'),
('CASHEW50', 'flat', 50.00, 299.00, 50.00, 500, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), '₹50 off on cashew products (min ₹299)'),
('MANGO20', 'percentage', 20.00, 999.00, 300.00, 300, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 60 DAY), '20% off on mango products (min ₹999)'),
('WELCOME15', 'percentage', 15.00, 0.00, 150.00, 2000, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), '15% off welcome coupon for new customers'),
('FESTIVE25', 'percentage', 25.00, 1499.00, 500.00, 200, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 45 DAY), '25% off festive special (min ₹1499)'),
('SEAFOOD10', 'percentage', 10.00, 749.00, 150.00, 500, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), '10% off on seafood orders above ₹749'),
('BOGOSNACKS', 'bogo', 0.00, 499.00, NULL, 300, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 90 DAY), 'Buy 1 Get 1 on select traditional Konkan snacks');

-- ============================================================
-- BANNERS
-- ============================================================
INSERT INTO banners (title, subtitle, image_url, link_url, position, sort_order, is_active) VALUES
('Fresh Mangos Arrived!', 'Premium Devgad Alphonso directly from farms', '/images/banners/mango-hero.jpg', '/categories/konkan-mangoes-fruits', 'hero', 1, 1),
('Monsoon Specials', 'Enjoy traditional Konkan snacks this rainy season', '/images/banners/monsoon-hero.jpg', '/categories/monsoon-specials', 'hero', 2, 1),
('Pure Cashew Nuts', 'Premium Goan cashews at best prices', '/images/banners/cashew-hero.jpg', '/categories/cashew-dry-fruits', 'hero', 3, 1),
('Buy ₹999+ Get Free Cashews', 'Free 250g premium roasted cashews on orders above ₹999', '/images/banners/offer-cashew.jpg', '/offers', 'mid', 1, 1),
('Monsoon Special: Dried Fish', 'Authentic Konkan dried fish at special prices', '/images/banners/offer-monsoon.jpg', '/categories/monsoon-specials', 'mid', 2, 1),
('Free Shipping', 'On orders above ₹499', '/images/banners/free-shipping.jpg', '/offers', 'sidebar', 1, 1);

-- ============================================================
-- FLASH SALES
-- ============================================================
INSERT INTO flash_sales (product_id, sale_price, original_price, quantity_limit, sold_count, starts_at, ends_at, is_active) VALUES
(1, 1599.00, 2499.00, 50, 15, NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 1),
(26, 349.00, 549.00, 100, 30, NOW(), DATE_ADD(NOW(), INTERVAL 5 DAY), 1),
(116, 449.00, 699.00, 80, 25, NOW(), DATE_ADD(NOW(), INTERVAL 10 DAY), 1);

-- ============================================================
-- BANK OFFERS
-- ============================================================
INSERT INTO bank_offers (bank_name, bank_code, logo_url, offer_title, offer_description, discount_type, min_order_amount, max_discount, is_active, valid_from, valid_until, terms_url, sort_order) VALUES
('HDFC Bank', 'HDFC', NULL, 'Up to ₹150 OFF on credit cards', 'Flat discount on HDFC Credit Card transactions', 'credit_card', 999.00, 150.00, 1, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), NULL, 1),
('ICICI Bank', 'ICICI', NULL, 'Up to ₹125 OFF on credit cards', 'Instant discount on ICICI Credit Card payments', 'credit_card', 999.00, 125.00, 1, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), NULL, 2),
('State Bank of India', 'SBI', NULL, '10% off on debit cards', '10% instant discount on SBI Debit Card transactions', 'debit_card', 1499.00, 200.00, 1, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), NULL, 3),
('Axis Bank', 'AXIS', NULL, '₹100 OFF on UPI payments', 'Flat ₹100 cashback on Axis UPI payments', 'upi', 799.00, 100.00, 1, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), NULL, 4),
('Kotak Mahindra Bank', 'KOTAK', NULL, 'No-cost EMI on orders above ₹2,999', 'Pay in easy EMI installments with zero interest', 'emi', 2999.00, NULL, 1, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), NULL, 5);

-- ============================================================
-- SAMPLE REVIEWS
-- ============================================================
INSERT INTO reviews (product_id, user_id, rating, title, body, is_verified_purchase, is_approved) VALUES
(1, 2, 5, 'Best Alphonso Mangoes Ever!', 'These Devgad Alphonso mangoes are incredible. So sweet and flavorful. The packaging was perfect and they arrived in great condition. Will definitely order again!', 1, 1),
(1, 3, 4, 'Very Good Quality', 'The mangoes were very fresh and sweet. A bit pricey but worth it for the quality. Gift packaging was beautiful.', 1, 1),
(2, 5, 5, 'Taste of Konkan', 'Brought back memories of my childhood in Ratnagiri. These mangoes are the real deal. Highly recommended!', 1, 1),
(26, 2, 5, 'Authentic Bombil', 'The dried bombil is excellent quality. Made traditional Konkan bombil fry and it tasted just like back home.', 1, 1),
(51, 3, 5, 'Pure Coconut Oil', 'This is the real deal - pure cold-pressed coconut oil with amazing aroma. Great for cooking and hair care.', 1, 1),
(66, 2, 5, 'Best Indrayani Rice', 'The aroma of this rice while cooking is incredible. Perfect for daily use and special occasions.', 1, 1),
(86, 4, 5, 'Refreshing Sol Kadhi', 'Perfect sol kadhi concentrate. Tastes just like homemade. Great for digestion after meals.', 1, 1),
(116, 5, 4, 'Crunchy and Fresh', 'The roasted cashews are very fresh and crunchy. Good value for the price.', 1, 1);

-- ============================================================
-- SITE SETTINGS (additional)
-- ============================================================
INSERT INTO site_settings (setting_key, value) VALUES
('homepage_meta_title', 'Konkan Bazaar - Authentic Konkan Products Online'),
('homepage_meta_description', 'Shop authentic Konkan region products including Alphonso mangoes, cashews, spices, seafood, and traditional delicacies. Direct from farmers and artisans of Konkan.'),
('about_us', 'Konkan Bazaar is your trusted online marketplace for authentic products from the Konkan region - the beautiful coastal belt of Maharashtra, Goa, and Karnataka. We connect you directly with local farmers, fishermen, and artisans who have been crafting these products for generations.'),
('returns_policy', 'We accept returns within 7 days of delivery for damaged or defective items. Perishable food items cannot be returned once opened.'),
('shipping_policy', 'Free shipping on orders above ₹499. Standard delivery within 3-5 business days. Express delivery available at extra charge.'),
('privacy_policy', 'We take your privacy seriously. Your personal information is encrypted and never shared with third parties without your consent.'),
('terms_of_service', 'By using Konkan Bazaar, you agree to our terms and conditions. All prices are in INR and inclusive of applicable taxes.');
